grammar = <|"source" -> "appendix G, the Gua product and its nine readers: alphabet, \
feature inventory and schemata", "alphabet" -> {"\[EmptySet]", "a", "\:025c",
   "\:025b", "e", "\:026a", "i", "\:0254", "o", "\:028a", "u", "j", "w"},
 "inventory" -> <|"\[EmptySet]" -> <|"nuclear" -> False, "present" -> False,
     "atr" -> Null, "quality" -> Null, "high" -> False|>,
   "a" -> <|"nuclear" -> True, "present" -> True, "atr" -> False,
     "quality" -> 0, "high" -> False|>,
   "\:025c" -> <|"nuclear" -> True, "present" -> True, "atr" -> True,
     "quality" -> 0, "high" -> False|>,
   "\:025b" -> <|"nuclear" -> True, "present" -> True, "atr" -> False,
     "quality" -> 1, "high" -> False|>,
   "e" -> <|"nuclear" -> True, "present" -> True, "atr" -> True,
     "quality" -> 1, "high" -> False|>,
   "\:026a" -> <|"nuclear" -> True, "present" -> True, "atr" -> False,
     "quality" -> 2, "high" -> True|>,
   "i" -> <|"nuclear" -> True, "present" -> True, "atr" -> True,
     "quality" -> 2, "high" -> True|>,
   "\:0254" -> <|"nuclear" -> True, "present" -> True, "atr" -> False,
     "quality" -> 3, "high" -> False|>,
   "o" -> <|"nuclear" -> True, "present" -> True, "atr" -> True,
     "quality" -> 3, "high" -> False|>,
   "\:028a" -> <|"nuclear" -> True, "present" -> True, "atr" -> False,
     "quality" -> 4, "high" -> True|>,
   "u" -> <|"nuclear" -> True, "present" -> True, "atr" -> True,
     "quality" -> 4, "high" -> True|>,
   "j" -> <|"nuclear" -> False, "present" -> True, "atr" -> Null,
     "quality" -> 2, "high" -> False|>,
   "w" -> <|"nuclear" -> False, "present" -> True, "atr" -> Null,
     "quality" -> 4, "high" -> False|>|>,
 "types" -> {"MAX", "IDENT_ATR", "IDENT_QUALITY", "IDENT_NUC", "H", "A",
   "GL", "D", "INITIAL_FEATURE"}|>;
inputsSelection = {<|"id" -> "G34a", "phase" -> "opaque",
  "slots" -> {<|"word" -> 0, "phone" -> "a"|>,
    <|"word" -> 0, "phone" -> "h"|>, <|"word" -> 0, "phone" -> "\:025b"|>,
    <|"word" -> 1, "phone" -> "t"|>, <|"word" -> 1, "phone" -> "e"|>,
    <|"word" -> 2, "phone" -> "\:0254"|>, <|"word" -> 2, "phone" -> "k"|>,
    <|"word" -> 2, "phone" -> "p"|>, <|"word" -> 2, "phone" -> "\:028a"|>,
    <|"word" -> 2, "phone" -> "k"|>, <|"word" -> 2, "phone" -> "\:0254"|>},
  "focal" -> {2, 4, 5}, "phrases" -> {0, 0, 0}|>,
 <|"id" -> "G34b", "phase" -> "opaque",
  "slots" -> {<|"word" -> 0, "phone" -> "a"|>,
    <|"word" -> 0, "phone" -> "f"|>, <|"word" -> 0, "phone" -> "\:026a"|>,
    <|"word" -> 1, "phone" -> "s"|>, <|"word" -> 1, "phone" -> "\:025b"|>,
    <|"word" -> 2, "phone" -> "o"|>, <|"word" -> 2, "phone" -> "h"|>,
    <|"word" -> 2, "phone" -> "i"|>, <|"word" -> 2, "phone" -> "l"|>,
    <|"word" -> 2, "phone" -> "i"|>}, "focal" -> {2, 4, 5},
  "phrases" -> {0, 0, 0}|>, <|"id" -> "N7", "phase" -> "opaque",
  "slots" -> {<|"word" -> 0, "phone" -> "a"|>,
    <|"word" -> 0, "phone" -> "t\:0283"|>, <|"word" -> 0,
     "phone" -> "\:026a"|>, <|"word" -> 1, "phone" -> "j"|>,
    <|"word" -> 1, "phone" -> "e"|>, <|"word" -> 1, "phone" -> "l"|>,
    <|"word" -> 1, "phone" -> "i"|>}, "focal" -> {2, 4},
  "phrases" -> {0, 0}|>, <|"id" -> "G37c", "phase" -> "opaque",
  "slots" -> {<|"word" -> 0, "phone" -> "\:0254"|>,
    <|"word" -> 0, "phone" -> "t\:0283"|>, <|"word" -> 0,
     "phone" -> "\:028a"|>, <|"word" -> 1, "phone" -> "s"|>,
    <|"word" -> 1, "phone" -> "\:025b"|>, <|"word" -> 2, "phone" -> "i"|>,
    <|"word" -> 2, "phone" -> "b"|>, <|"word" -> 2, "phone" -> "i"|>,
    <|"word" -> 2, "phone" -> "e"|>}, "focal" -> {2, 4, 5},
  "phrases" -> {0, 0, 0}|>, <|"id" -> "C24ei", "phase" -> "control",
  "slots" -> {<|"word" -> 0, "phone" -> "k"|>,
    <|"word" -> 0, "phone" -> "p"|>, <|"word" -> 0, "phone" -> "e"|>,
    <|"word" -> 1, "phone" -> "i"|>, <|"word" -> 1, "phone" -> "s"|>,
    <|"word" -> 1, "phone" -> "i"|>}, "focal" -> {2, 3},
  "phrases" -> {0, 0}|>};
inputsDeletion = {<|"id" -> "OR38", "phase" -> "opaque",
  "slots" -> {<|"word" -> 0, "phone" -> "a"|>,
    <|"word" -> 0, "phone" -> "t\:0283"|>, <|"word" -> 0,
     "phone" -> "\:0254"|>, <|"word" -> 1, "phone" -> "s"|>,
    <|"word" -> 1, "phone" -> "\:026a"|>, <|"word" -> 2, "phone" -> "i"|>,
    <|"word" -> 2, "phone" -> "k"|>, <|"word" -> 2, "phone" -> "u"|>},
  "focal" -> {2, 4, 5}, "phrases" -> {0, 0, 0}|>,
 <|"id" -> "C21b", "phase" -> "control",
  "slots" -> {<|"word" -> 0, "phone" -> "w"|>,
    <|"word" -> 0, "phone" -> "\:028a"|>, <|"word" -> 0, "phone" -> "s"|>,
    <|"word" -> 0, "phone" -> "\:028a"|>, <|"word" -> 1,
     "phone" -> "\:026a"|>, <|"word" -> 1, "phone" -> "s"|>,
    <|"word" -> 1, "phone" -> "\:025b"|>}, "focal" -> {3, 4},
  "phrases" -> {0, 0}|>, <|"id" -> "C23UE", "phase" -> "control",
  "slots" -> {<|"word" -> 0, "phone" -> "w"|>,
    <|"word" -> 0, "phone" -> "\:028a"|>, <|"word" -> 0, "phone" -> "s"|>,
    <|"word" -> 0, "phone" -> "\:028a"|>, <|"word" -> 1,
     "phone" -> "\:025b"|>, <|"word" -> 1, "phone" -> "b"|>,
    <|"word" -> 1, "phone" -> "\:026a"|>}, "focal" -> {3, 4},
  "phrases" -> {0, 0}|>};
observationsSelection = {<|"id" -> "G34a", "source" -> "Obiri-Yeboah & Rasin (2025)",
  "source_segmental_input" -> "ah\:025b te \:0254kp\:028ak\:0254",
  "source_segmental_output" -> "ahe t\:0254 \:0254kp\:028ak\:0254",
  "allowed" -> {"ahet\:0254\:0254kp\:028ak\:0254"}, "negative" -> {},
  "scope" -> "full segment sequence; supplied phrasing recorded separately; \
tone/quantity/syllabification/lexical surface boundary not predicted",
  "categorical_singleton_is_hypothesis" -> True|>,
 <|"id" -> "G34b", "source" -> "Obiri-Yeboah & Rasin (2025)",
  "source_segmental_input" -> "af\:026a s\:025b ohili",
  "source_segmental_output" -> "af\:026a so ohili",
  "allowed" -> {"af\:026asoohili"}, "negative" -> {"afisoohili"},
  "scope" -> "full segment sequence; supplied phrasing recorded separately; \
tone/quantity/syllabification/lexical surface boundary not predicted",
  "categorical_singleton_is_hypothesis" -> True|>,
 <|"id" -> "N7", "source" -> "Obiri-Yeboah & Rasin (2025)",
  "source_segmental_input" -> "at\:0283\:026a jeli",
  "source_segmental_output" -> "at\:0283i jeli",
  "allowed" -> {"at\:0283ijeli"}, "negative" -> {},
  "scope" -> "full segment sequence; supplied phrasing recorded separately; \
tone/quantity/syllabification/lexical surface boundary not predicted",
  "categorical_singleton_is_hypothesis" -> True|>,
 <|"id" -> "G37c", "source" -> "Obiri-Yeboah & Rasin (2025)",
  "source_segmental_input" -> "\:0254t\:0283\:028a s\:025b ibie",
  "source_segmental_output" -> "\:0254t\:0283\:028a sejbie",
  "allowed" -> {"\:0254t\:0283\:028asejbie"}, "negative" -> {},
  "scope" -> "full segment sequence; supplied phrasing recorded separately; \
tone/quantity/syllabification/lexical surface boundary not predicted",
  "categorical_singleton_is_hypothesis" -> True|>,
 <|"id" -> "C24ei", "source" -> "Obiri-Yeboah & Rasin (2025)",
  "source_segmental_input" -> "kpe isi", "source_segmental_output" ->
   "kpe jsi", "allowed" -> {"kpejsi"}, "negative" -> {},
  "scope" -> "full segment sequence; supplied phrasing recorded separately; \
tone/quantity/syllabification/lexical surface boundary not predicted",
  "categorical_singleton_is_hypothesis" -> True|>};
observationsDeletion = {<|"id" -> "OR38", "source" -> "Obiri-Yeboah & Rasin (2025)",
  "source_segmental_input" -> "at\:0283\:0254 s\:026a iku",
  "source_segmental_output" -> "at\:0283\:0254 siku",
  "allowed" -> {"at\:0283\:0254siku"}, "negative" -> {},
  "scope" -> "full segment sequence; supplied phrasing recorded separately; \
tone/quantity/syllabification/lexical surface boundary not predicted",
  "categorical_singleton_is_hypothesis" -> True|>,
 <|"id" -> "C21b", "source" -> "Obiri-Yeboah & Rasin (2025)",
  "source_segmental_input" -> "w\:028as\:028a \:026as\:025b",
  "source_segmental_output" -> "w\:028as\:028a s\:025b",
  "allowed" -> {"w\:028as\:028as\:025b"}, "negative" -> {},
  "scope" -> "full segment sequence; supplied phrasing recorded separately; \
tone/quantity/syllabification/lexical surface boundary not predicted",
  "categorical_singleton_is_hypothesis" -> True|>,
 <|"id" -> "C23UE", "source" -> "Obiri-Yeboah & Rasin (2025)",
  "source_segmental_input" -> "w\:028as\:028a \:025bb\:026a",
  "source_segmental_output" -> "w\:028asw \:025bb\:026a",
  "allowed" -> {"w\:028asw\:025bb\:026a"}, "negative" -> {},
  "scope" -> "full segment sequence; supplied phrasing recorded separately; \
tone/quantity/syllabification/lexical surface boundary not predicted",
  "categorical_singleton_is_hypothesis" -> True|>};
probe = <|"id" -> "constructed_A_locality",
 "slots" -> {<|"word" -> 0, "phone" -> "e"|>,
   <|"word" -> 1, "phone" -> "o"|>, <|"word" -> 2, "phone" -> "e"|>,
   <|"word" -> 3, "phone" -> "e"|>}, "focal" -> {0, 1, 2, 3},
 "phrases" -> {0, 0, 1, 1}, "states" -> {{"e", "\[EmptySet]", "e", "e"},
   {"e", "\[EmptySet]", "o", "e"}}, "origin_index" -> 0, "schema_index" -> 5,
 "status" -> "constructed reader probe; not an attested form or full-product \
selecting test"|>;
