import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Analysis.SpecialFunctions.Pow.Real
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Positivity
import Mathlib.Tactic.Ring

/-!
# Contact-response algebra

This module verifies the exact algebraic components of the support-boundary
contact-response theorem.  It distinguishes the drop-flux and response loads,
checks the two registered contact coefficients, and proves the Lambert
normal-form identity, exact coefficient recovery, and logarithmic slope limit
from the defining equation.  The general KKT singular-perturbation and
remainder-transfer claims require additional analytic formalization.
-/

namespace PhonologicalCalculus.Flux

open Filter

/-- Markedness-to-edge-weight ratio governing a full drop. -/
noncomputable def dropScale (h m : ℝ) : ℝ := m / h

/-- Markedness-to-marginal-weight ratio governing a support response. -/
noncomputable def responseScale (h m p : ℝ) : ℝ := m / (h * p)

/-- **FLUX-D4.SCALES.01.**  The drop scale is exactly `p` times the response
scale. -/
theorem flux_d4_scales_01 {h m p : ℝ} (hh : h ≠ 0) (hp : p ≠ 0) :
    dropScale h m = p * responseScale h m p := by
  unfold dropScale responseScale
  field_simp [hh, hp]

/-- Quadratic-baseline coefficient generated by a contact of order `nu`. -/
noncomputable def contactCoefficientQuadratic
    (lambda A : ℝ) (nu : ℕ) (kappa : ℝ) : ℝ :=
  kappa / lambda * (1 + 1 / A ^ nu)

/-- **FLUX-D4.COEFFICIENTS.02.**  Exact regular- and cubic-contact
coefficients for the registered parameters. -/
theorem flux_d4_coefficients_02 :
    contactCoefficientQuadratic (1 / 10) 4 1 1 = 25 / 2 ∧
      contactCoefficientQuadratic (1 / 10) 4 3
          (200 * Real.pi ^ 2 / 3) = 8125 * Real.pi ^ 2 / 12 := by
  constructor <;> unfold contactCoefficientQuadratic
  · norm_num
  · ring

/-- The response exponent determined by contact order and edge exponent. -/
def responseExponent (nu : ℕ) (p : ℝ) : ℝ :=
  nu * min 1 (p - 1)

/-- Below the quadratic threshold, the response exponent is
`nu * (p - 1)`. -/
theorem responseExponent_of_le_two {nu : ℕ} {p : ℝ}
    (hpTwo : p ≤ 2) :
    responseExponent nu p = nu * (p - 1) := by
  unfold responseExponent
  rw [min_eq_right]
  linarith

/-- At and above the quadratic threshold, the response exponent is the
contact order itself. -/
theorem responseExponent_of_two_le {nu : ℕ} {p : ℝ} (hpTwo : 2 ≤ p) :
    responseExponent nu p = nu := by
  unfold responseExponent
  rw [min_eq_left]
  · norm_num
  · linarith

/-- The defining relation required of the positive real Lambert branch. -/
def LambertWitness (z w : ℝ) : Prop :=
  w * Real.exp w = z

/-- The printed Lambert normal-form scale. -/
noncomputable def lambertNormalT (epsilon Gamma C w : ℝ) : ℝ :=
  (epsilon * w / (Gamma * C)) ^ (1 / Gamma : ℝ)

/-- A positive Lambert witness rewrites the base of the normal form as
`exp (-w)`. -/
theorem lambert_base_eq_exp_neg {epsilon Gamma C w : ℝ}
    (hepsilon : 0 < epsilon) (hGamma : 0 < Gamma) (hC : 0 < C)
    (_hw : 0 < w)
    (hLambert : LambertWitness (Gamma * C / epsilon) w) :
    epsilon * w / (Gamma * C) = Real.exp (-w) := by
  unfold LambertWitness at hLambert
  have hexp : Real.exp w ≠ 0 := ne_of_gt (Real.exp_pos w)
  have hepsilon0 : epsilon ≠ 0 := ne_of_gt hepsilon
  have hGamma0 : Gamma ≠ 0 := ne_of_gt hGamma
  have hC0 : C ≠ 0 := ne_of_gt hC
  have hmul : w * Real.exp w * epsilon = Gamma * C :=
    (eq_div_iff hepsilon0).mp hLambert
  rw [Real.exp_neg]
  field_simp [hepsilon0, hGamma0, hC0, hexp]
  calc
    epsilon * w * Real.exp w = w * Real.exp w * epsilon := by ring
    _ = Gamma * C := hmul

/-- The Lambert normal-form scale is exactly `exp (-w/Gamma)` under the
defining Lambert equation. -/
theorem lambertNormalT_eq_exp {epsilon Gamma C w : ℝ}
    (hepsilon : 0 < epsilon) (hGamma : 0 < Gamma) (hC : 0 < C)
    (hw : 0 < w)
    (hLambert : LambertWitness (Gamma * C / epsilon) w) :
    lambertNormalT epsilon Gamma C w = Real.exp (-w / Gamma) := by
  have hbase := lambert_base_eq_exp_neg hepsilon hGamma hC hw hLambert
  unfold lambertNormalT
  rw [hbase, Real.rpow_def_of_pos (Real.exp_pos (-w))]
  rw [Real.log_exp]
  congr 1
  field_simp [ne_of_gt hGamma]

/-- Exact algebraic inversion underlying the Lambert normal form.  This is
the identity clause of FLUX-D4.NORMALFORM.03; its two asymptotic limit clauses
are not asserted by this declaration. -/
theorem lambert_normal_form_identity {epsilon Gamma C w : ℝ}
    (hepsilon : 0 < epsilon) (hGamma : 0 < Gamma) (hC : 0 < C)
    (hw : 0 < w)
    (hLambert : LambertWitness (Gamma * C / epsilon) w) :
    C * (lambertNormalT epsilon Gamma C w) ^ Gamma /
        (-Real.log (lambertNormalT epsilon Gamma C w)) = epsilon := by
  have ht := lambertNormalT_eq_exp hepsilon hGamma hC hw hLambert
  have hGamma0 : Gamma ≠ 0 := ne_of_gt hGamma
  have hw0 : w ≠ 0 := ne_of_gt hw
  rw [ht]
  have hpow : (Real.exp (-w / Gamma)) ^ Gamma = Real.exp (-w) := by
    rw [Real.rpow_def_of_pos (Real.exp_pos (-w / Gamma)), Real.log_exp]
    congr 1
    field_simp [hGamma0]
  rw [hpow, Real.log_exp]
  have hbase := lambert_base_eq_exp_neg hepsilon hGamma hC hw hLambert
  have hden : -(-w / Gamma) ≠ 0 :=
    neg_ne_zero.mpr (div_ne_zero (neg_ne_zero.mpr hw0) hGamma0)
  rw [← hbase]
  field_simp [hGamma0, ne_of_gt hC, hden]

/-- The coefficient recovered from the exact Lambert response is identically
`C`, not merely convergent to it.  Consequently every admissible parameter
path has the registered coefficient limit whenever it approaches the contact
face. -/
theorem lambert_normal_form_coefficient {epsilon Gamma C w : ℝ}
    (hepsilon : 0 < epsilon) (hGamma : 0 < Gamma) (hC : 0 < C)
    (hw : 0 < w)
    (hLambert : LambertWitness (Gamma * C / epsilon) w) :
    epsilon /
        ((lambertNormalT epsilon Gamma C w) ^ Gamma /
          (-Real.log (lambertNormalT epsilon Gamma C w))) = C := by
  have ht := lambertNormalT_eq_exp hepsilon hGamma hC hw hLambert
  have hGamma0 : Gamma ≠ 0 := ne_of_gt hGamma
  have htPositive : 0 < lambertNormalT epsilon Gamma C w := by
    rw [ht]
    exact Real.exp_pos _
  have hlog : -Real.log (lambertNormalT epsilon Gamma C w) ≠ 0 := by
    rw [ht, Real.log_exp]
    exact neg_ne_zero.mpr (div_ne_zero (neg_ne_zero.mpr (ne_of_gt hw)) hGamma0)
  have hratio :
      (lambertNormalT epsilon Gamma C w) ^ Gamma /
          (-Real.log (lambertNormalT epsilon Gamma C w)) ≠ 0 :=
    div_ne_zero (ne_of_gt (Real.rpow_pos_of_pos htPositive Gamma)) hlog
  rw [div_eq_iff hratio]
  calc
    epsilon = C * (lambertNormalT epsilon Gamma C w) ^ Gamma /
        (-Real.log (lambertNormalT epsilon Gamma C w)) :=
      (lambert_normal_form_identity hepsilon hGamma hC hw hLambert).symm
    _ = C * ((lambertNormalT epsilon Gamma C w) ^ Gamma /
        (-Real.log (lambertNormalT epsilon Gamma C w))) := by ring

/-- **FLUX-D4.NORMALFORM.03, logarithmic slope.**  Parameterizing the positive
Lambert branch by its witness `w`, the logarithmic response slope converges to
`1 / Gamma`.  This avoids postulating a special-function implementation: the
parameterization is exactly the defining equation `w * exp w = Gamma*C/epsilon`.
-/
theorem lambert_log_slope_atTop {Gamma C : ℝ}
    (hGamma : 0 < Gamma) (hC : 0 < C) :
    Tendsto
      (fun w : ℝ =>
        Real.log (Real.exp (-w / Gamma)) /
          Real.log (Gamma * C / (w * Real.exp w)))
      atTop (nhds (1 / Gamma)) := by
  have hGamma0 : Gamma ≠ 0 := ne_of_gt hGamma
  have hGC0 : Gamma * C ≠ 0 := mul_ne_zero hGamma0 (ne_of_gt hC)
  have hlogOverId : Tendsto (fun w : ℝ => Real.log w / w)
      atTop (nhds 0) :=
    Real.isLittleO_log_id_atTop.tendsto_div_nhds_zero
  have hconstOverId : Tendsto (fun w : ℝ => Real.log (Gamma * C) / w)
      atTop (nhds 0) :=
    tendsto_id.const_div_atTop (Real.log (Gamma * C))
  have hdenNormalized : Tendsto
      (fun w : ℝ =>
        (Real.log (Gamma * C) - Real.log w - w) / w)
      atTop (nhds (-1)) := by
    have hparts :=
      (hconstOverId.sub hlogOverId).sub
        (tendsto_const_nhds : Tendsto (fun _ : ℝ => (1 : ℝ)) atTop (nhds 1))
    simpa using hparts.congr' (by
      filter_upwards [eventually_ne_atTop (0 : ℝ)] with w hw
      field_simp [hw])
  have hnumNormalized : Tendsto
      (fun w : ℝ => (-w / Gamma) / w)
      atTop (nhds (-1 / Gamma)) := by
    apply tendsto_const_nhds.congr'
    filter_upwards [eventually_ne_atTop (0 : ℝ)] with w hw
    field_simp [hw, hGamma0]
  have hnormalizedRatio : Tendsto
      (fun w : ℝ =>
        ((-w / Gamma) / w) /
          ((Real.log (Gamma * C) - Real.log w - w) / w))
      atTop (nhds (1 / Gamma)) := by
    have hquot := hnumNormalized.div hdenNormalized (by norm_num)
    change Tendsto
      (fun w : ℝ =>
        ((-w / Gamma) / w) /
          ((Real.log (Gamma * C) - Real.log w - w) / w))
      atTop (nhds ((-1 / Gamma) / (-1))) at hquot
    have hlimit : (-1 / Gamma) / (-1) = 1 / Gamma := by
      field_simp [hGamma0]
    rw [hlimit] at hquot
    exact hquot
  apply hnormalizedRatio.congr'
  filter_upwards [eventually_gt_atTop (0 : ℝ)] with w hw
  have hw0 : w ≠ 0 := ne_of_gt hw
  have hexp0 : Real.exp w ≠ 0 := ne_of_gt (Real.exp_pos w)
  rw [Real.log_exp, Real.log_div hGC0 (mul_ne_zero hw0 hexp0),
    Real.log_mul hw0 hexp0, Real.log_exp]
  field_simp [hw0]
  ring

end PhonologicalCalculus.Flux
