SPEC = {'version': '1.0.0',
 'provenance': {'note': "This file is a declarative restatement of the dissertation's primitive "
                        'definitions. It is NOT a copy of any precomputed score table. Independent '
                        'Python and Wolfram interpreters must each derive scores from these fields '
                        'alone.'},
 'alphabet': ['∅', 'a', 'ɜ', 'ɛ', 'e', 'ɪ', 'i', 'ɔ', 'o', 'ʊ', 'u', 'j', 'w'],
 'features': {'∅': {'present': False,
                    'nuclear': False,
                    'quality': None,
                    'atr': None,
                    'high': False},
              'a': {'present': True, 'nuclear': True, 'quality': 0, 'atr': False, 'high': False},
              'ɜ': {'present': True, 'nuclear': True, 'quality': 0, 'atr': True, 'high': False},
              'ɛ': {'present': True, 'nuclear': True, 'quality': 1, 'atr': False, 'high': False},
              'e': {'present': True, 'nuclear': True, 'quality': 1, 'atr': True, 'high': False},
              'ɪ': {'present': True, 'nuclear': True, 'quality': 2, 'atr': False, 'high': True},
              'i': {'present': True, 'nuclear': True, 'quality': 2, 'atr': True, 'high': True},
              'ɔ': {'present': True, 'nuclear': True, 'quality': 3, 'atr': False, 'high': False},
              'o': {'present': True, 'nuclear': True, 'quality': 3, 'atr': True, 'high': False},
              'ʊ': {'present': True, 'nuclear': True, 'quality': 4, 'atr': False, 'high': True},
              'u': {'present': True, 'nuclear': True, 'quality': 4, 'atr': True, 'high': True},
              'j': {'present': True, 'nuclear': False, 'quality': 2, 'atr': None, 'high': False},
              'w': {'present': True, 'nuclear': False, 'quality': 4, 'atr': None, 'high': False}},
 'default_segment_features': {'present': True,
                              'nuclear': False,
                              'quality': None,
                              'atr': None,
                              'high': False},
 'schemas': [{'name': 'MAX',
              'kind': 'faithfulness',
              'index': 0,
              'context': 'always',
              'definedness': 'always',
              'consequence': 'target_present'},
             {'name': 'IDENT_ATR',
              'kind': 'faithfulness',
              'index': 1,
              'context': 'always',
              'definedness': 'reference_nuclear_and_candidate_nuclear',
              'consequence': 'atr_equals_reference'},
             {'name': 'IDENT_QUAL',
              'kind': 'faithfulness',
              'index': 2,
              'context': 'always',
              'definedness': 'target_present_and_both_qualities_defined',
              'consequence': 'quality_equals_reference'},
             {'name': 'IDENT_NUC',
              'kind': 'faithfulness',
              'index': 3,
              'context': 'always',
              'definedness': 'target_present',
              'consequence': 'nuclearity_equals_reference'},
             {'name': 'H',
              'kind': 'markedness',
              'index': 4,
              'context': 'nuclear_target_last_current_nucleus_of_word_with_atr_positive_H_source',
              'definedness': 'target_nuclear',
              'consequence': 'target_atr_positive'},
             {'name': 'A',
              'kind': 'markedness',
              'index': 5,
              'context': 'target_and_next_present_origin_nuclear_nonhigh_consecutive_words_same_phrase',
              'definedness': 'always',
              'consequence': 'target_absent_or_same_segment_as_next_present_origin'},
             {'name': 'GL',
              'kind': 'markedness',
              'index': 6,
              'context': 'high_nuclear_target_with_nonhigh_nuclear_present_neighbour_in_consecutive_word_same_phrase',
              'definedness': 'always',
              'consequence': 'target_nonnuclear'},
             {'name': 'D',
              'kind': 'markedness',
              'index': 7,
              'context': 'high_nuclear_target_with_high_nuclear_preceding_present_origin_in_immediately_preceding_word_same_phrase',
              'definedness': 'always',
              'consequence': 'target_absent'},
             {'name': 'INITIAL_FEATURE',
              'kind': 'faithfulness',
              'index': 8,
              'context': 'reference_nuclear_and_first_lexical_segment_of_its_word',
              'definedness': 'target_present_with_defined_quality',
              'consequence': 'quality_equals_reference_and_if_nuclear_atr_equals_reference'}],
 'weights': {'MAX': 20,
             'IDENT_ATR': 1,
             'IDENT_QUAL': 1,
             'IDENT_NUC': 2,
             'H': 4,
             'A': 8,
             'GL': 8,
             'D': 24,
             'INITIAL_FEATURE': 1},
 'lambda': {'num': 1, 'den': 8},
 'score_scaling': {'integer_unit_denominator': 8},
 'inputs': [{'id': 'G34a',
             'phase': 'opaque',
             'words': [['a', 'h', 'ɛ'], ['t', 'e'], ['ɔ', 'k', 'p', 'ʊ', 'k', 'ɔ']],
             'phrases': [0, 0, 0],
             'focal': [2, 4, 5],
             'source': 'Obiri-Yeboah & Rasin 2025, p. 18 (34a)',
             'observation': 'ahetɔɔkpʊkɔ'},
            {'id': 'G34b',
             'phase': 'opaque',
             'words': [['a', 'f', 'ɪ'], ['s', 'ɛ'], ['o', 'h', 'i', 'l', 'i']],
             'phrases': [0, 0, 0],
             'focal': [2, 4, 5],
             'source': 'Obiri-Yeboah & Rasin 2025, p. 18 (34b); p. 19 (36)',
             'observation': 'afɪsoohili'},
            {'id': 'N7',
             'phase': 'transparent',
             'words': [['a', 'tʃ', 'ɪ'], ['j', 'e', 'l', 'i']],
             'phrases': [0, 0],
             'focal': [2, 4],
             'source': 'Obiri-Yeboah & Rasin 2025, p. 19 note 7',
             'observation': 'atʃijeli'},
            {'id': 'G37c',
             'phase': 'mixed',
             'words': [['ɔ', 'tʃ', 'ʊ'], ['s', 'ɛ'], ['i', 'b', 'i', 'e']],
             'phrases': [0, 0, 0],
             'focal': [2, 4, 5],
             'source': 'Obiri-Yeboah & Rasin 2025, p. 20 (37c)',
             'observation': 'ɔtʃʊsejbie'},
            {'id': 'C24ei',
             'phase': 'transparent',
             'words': [['k', 'p', 'e'], ['i', 's', 'i']],
             'phrases': [0, 0],
             'focal': [2, 3],
             'source': 'Obiri-Yeboah & Rasin 2025, pp. 12-13 (24), e/i cell',
             'observation': 'kpejsi'},
            {'id': 'OR38',
             'phase': 'deletion',
             'words': [['a', 'tʃ', 'ɔ'], ['s', 'ɪ'], ['i', 'k', 'u']],
             'phrases': [0, 0, 0],
             'focal': [2, 4, 5],
             'source': 'Obiri-Yeboah & Rasin 2025, p. 20 (38a); elicitation sentence created in '
                       'the source',
             'observation': 'atʃɔsiku'},
            {'id': 'C21b',
             'phase': 'deletion',
             'words': [['w', 'ʊ', 's', 'ʊ'], ['ɪ', 's', 'ɛ']],
             'phrases': [0, 0],
             'focal': [3, 4],
             'source': 'Obiri-Yeboah & Rasin 2025, pp. 12-13 (21b)/(23)',
             'observation': 'wʊsʊsɛ'},
            {'id': 'C23UE',
             'phase': 'glide',
             'words': [['w', 'ʊ', 's', 'ʊ'], ['ɛ', 'b', 'ɪ']],
             'phrases': [0, 0],
             'focal': [3, 4],
             'source': 'Obiri-Yeboah & Rasin 2025, pp. 12-13 (23), ʊ/ɛ cell',
             'observation': 'wʊswɛbɪ'}],
 'expected_regression': {'total_candidates': 9464,
                         'per_input': {'G34a': {'states': 2197,
                                                'fiber': [774],
                                                'minima': [774],
                                                'minimum8': 24},
                                       'G34b': {'states': 2197,
                                                'fiber': [957],
                                                'minima': [957],
                                                'minimum8': 20},
                                       'N7': {'states': 169,
                                              'fiber': [82],
                                              'minima': [82],
                                              'minimum8': 8},
                                       'G37c': {'states': 2197,
                                                'fiber': [1584],
                                                'minima': [1584],
                                                'minimum8': 28},
                                       'C24ei': {'states': 169,
                                                 'fiber': [63],
                                                 'minima': [63],
                                                 'minimum8': 16},
                                       'OR38': {'states': 2197,
                                                'fiber': [1189, 1261],
                                                'minima': [1261],
                                                'minimum8': 172},
                                       'C21b': {'states': 169,
                                                'fiber': [9, 117],
                                                'minima': [117],
                                                'minimum8': 160},
                                       'C23UE': {'states': 169,
                                                 'fiber': [159],
                                                 'minima': [159],
                                                 'minimum8': 16}}},
 'probes': [{'id': 'constructed_A_locality',
             'role': 'appendix G.6 compositional-limit witness; constructed reader probe, not an '
                     'attested form and not a full-product selection result',
             'words': [['e'], ['o'], ['e'], ['e']],
             'phrases': [0, 0, 1, 1],
             'focal': [0, 1, 2, 3],
             'states': [['e', '∅', 'e', 'e'], ['e', '∅', 'o', 'e']],
             'locus': {'origin': 0, 'schema': 'A'},
             'expected': {'context': [False, False],
                          'defined': [True, True],
                          'good': [True, False],
                          'retained8': [0, 64],
                          'first_phrase_projection_equal': True}}]}
