SPEC = {'version': '1.0.0',
 'provenance': {},
 'index': 'j = 4x + 2y + z',
 'inputs': [{'id': 'PG',
             'morpheme': '/ap-gauti/',
             'prefix': ['p', 'b'],
             'stem': ['k', 'g'],
             'tail': 'auti',
             'reference_bits': [0, 1, 0],
             'h': 0,
             'observation': 'abgauti'},
            {'id': 'PB',
             'morpheme': '/ap-berti/',
             'prefix': ['p', 'b'],
             'stem': ['p', 'b'],
             'tail': 'erti',
             'reference_bits': [0, 1, 0],
             'h': 1,
             'observation': 'apiberti'},
            {'id': 'TT',
             'morpheme': '/at-taiki:ti/',
             'prefix': ['t', 'd'],
             'stem': ['t', 'd'],
             'tail': 'aiki:ti',
             'reference_bits': [0, 0, 0],
             'h': 1,
             'observation': 'atitaiki:ti'}],
 'markedness': {'A': {'context': '1-z', 'consequence': '[x = y]'},
                'N': {'context': '1-z', 'consequence': '1 - h[x = y]'}},
 'faithfulness': 'F = c[x != 0] + r[y != y_U] + d z',
 'parameters': {'names': ['c', 'r', 'd', 'a', 'n', 'lambda'], 'nonnegative': True},
 'reference_point': {'c': 1, 'r': 4, 'd': 2, 'a': 16, 'n': 16, 'lambda': [1, 8]},
 'expected_regression': {'correct_fibers': {'PG': [6], 'PB': [3], 'TT': [1]},
                         'minimum8_at_reference_point': {'O': {'PG': 8, 'PB': 16, 'TT': 16},
                                                         'RR': {'PG': 8, 'PB': 16, 'TT': 16},
                                                         'SR': {'PG': 8, 'PB': 24, 'TT': 16},
                                                         'RS': {'PG': 8, 'PB': 16, 'TT': 24},
                                                         'SS': {'PG': 8, 'PB': 24, 'TT': 24},
                                                         'RR0': {'PG': 8, 'PB': 8, 'TT': 8}},
                         'exclusively_correct_at_reference_point': {'O': {'PG': True,
                                                                          'PB': True,
                                                                          'TT': True},
                                                                    'RR': {'PG': True,
                                                                           'PB': True,
                                                                           'TT': True},
                                                                    'SR': {'PG': True,
                                                                           'PB': False,
                                                                           'TT': True},
                                                                    'RS': {'PG': True,
                                                                           'PB': True,
                                                                           'TT': False},
                                                                    'SS': {'PG': True,
                                                                           'PB': False,
                                                                           'TT': False},
                                                                    'RR0': {'PG': True,
                                                                            'PB': False,
                                                                            'TT': False}},
                         'region_RR': ['0 < c',
                                       'c < d',
                                       'c < r',
                                       'd < a',
                                       'd < n',
                                       'd < c + lambda*n',
                                       'd < c + lambda*a'],
                         'excluded': ['SR', 'RS', 'SS', 'RR with lambda = 0'],
                         'minima_at_reference_point': {'O': {'PG': [6], 'PB': [3], 'TT': [1]},
                                                       'RR': {'PG': [6], 'PB': [3], 'TT': [1]},
                                                       'SR': {'PG': [6], 'PB': [6, 7], 'TT': [1]},
                                                       'RS': {'PG': [6], 'PB': [3], 'TT': [4, 5]},
                                                       'SS': {'PG': [6],
                                                              'PB': [6, 7],
                                                              'TT': [4, 5]},
                                                       'RR0': {'PG': [6], 'PB': [6], 'TT': [4]}}}}
