vars = {wDep, wIdant, wIdcont, wIddor, wIdfront, wIdglottal, wIdhigh, wIdhtone, wIdlab, wIdnas, wIdnuclear, wIdobs, wIdround, wIdseg, wMax, wMutant, wMutdor, wNocoda, wSync, lam};
nonneg = And @@ (# >= 0 & /@ vars);
cons = And[
  -wIdant + wIdcont > 0,
  -wIdant + wIdcont + wIdfront + wIdhigh + wIdhtone + wIdlab + wIdnuclear + wIdobs + wMutdor > 0,
  -wIdant + wIdcont + wIdfront + wIdhigh + wIdlab + wIdnuclear + wIdobs + wMutdor + wSync*lam > 0,
  -wIdant + wIdcont + wIdfront + wIdhtone + wIdlab + wIdnuclear + wIdobs + wMutdor > 0,
  -wIdant + wIdcont + wIdfront + wIdhtone + wIdlab + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdcont + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdcont + wIdfront + wIdlab + wIdnuclear + wIdobs + wMutdor > 0,
  -wIdant + wIdcont + wIdfront + wIdlab + wIdnuclear + wIdobs + wMutdor*lam + wMutdor + 2*wNocoda*lam > 0,
  -wIdant + wIdcont + wIdfront + wIdlab + wIdobs + wMutdor > 0,
  -wIdant + wIdcont + wIdfront + wIdnuclear + wIdobs + wMutdor*lam + wMutdor + 2*wNocoda*lam > 0,
  -wIdant + wIdcont + wIdglottal > 0,
  -wIdant + wIdcont + wIdglottal + wIdlab + wMutdor > 0,
  -wIdant + wIdcont + wIdglottal + wMutdor > 0,
  -wIdant + wIdcont + wIdhigh + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIdant + wIdcont + wIdhigh + wIdlab + wIdnuclear + wIdobs + wIdround + wMutdor + wSync*lam > 0,
  -wIdant + wIdcont + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIdant + wIdcont + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdround + wMutdor*lam + wMutdor + 2*wNocoda*lam > 0,
  -wIdant + wIdcont + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor*lam + wMutdor + 2*wNocoda*lam > 0,
  -wIdant + wIdcont + wIdlab > 0,
  -wIdant + wIdcont + wIdlab + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIdant + wIdcont + wIdlab + wIdnuclear + wIdobs + wIdround + wMutdor + 2*wNocoda*lam > 0,
  -wIdant + wIdcont + wIdnuclear + wIdobs + wIdround + wMutdor + 2*wNocoda*lam > 0,
  -wIdant + wIdcont + wMutdor*lam + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdglottal + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wMutdor + wSync*lam > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdglottal + wIdnuclear + wIdobs + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdglottal + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdglottal + wIdobs + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutdor + wSync*lam > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdhtone + wIdlab + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdlab + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdnuclear + wIdobs + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdobs + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdglottal + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wIdround + wMutdor + wSync*lam > 0,
  -wIdant + wIdcont - wIddor + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdcont - wIddor + wIdglottal + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdglottal + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdcont - wIddor + wIdglottal + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdhigh + wIdnuclear + wIdobs + wIdround + wMutdor + wSync*lam > 0,
  -wIdant + wIdcont - wIddor + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdround + wMutdor + 2*wNocoda*lam > 0,
  -wIdant + wIdcont - wIddor + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor + 2*wNocoda*lam > 0,
  -wIdant + wIdcont - wIddor + wIdlab + wIdnuclear + wIdobs + wIdround + wMutdor + 2*wNocoda*lam > 0,
  -wIdant + wIdcont - wIddor + wIdlab + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdnas + wIdobs + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdnuclear + wIdobs + wIdround + wMutdor + 2*wNocoda*lam > 0,
  -wIdant + wIdcont - wIddor + wMutdor > 0,
  -wIdant + wIdfront + wIdhigh + wIdhtone + wIdnuclear + wIdobs > 0,
  -wIdant + wIdfront + wIdhigh + wIdnuclear + wIdobs + wSync*lam > 0,
  -wIdant + wIdfront + wIdhtone + wIdnuclear + wIdobs > 0,
  -wIdant + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdfront + wIdnuclear + wIdobs > 0,
  -wIdant + wIdfront + wIdnuclear + wIdobs + wMutdor*lam + wMutdor + 2*wNocoda*lam > 0,
  -wIdant + wIdfront + wIdobs > 0,
  -wIdant + wIdglottal > 0,
  -wIdant + wIdglottal + wIdlab + wMutdor > 0,
  -wIdant + wIdglottal + wMutdor > 0,
  -wIdant + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wIdround > 0,
  -wIdant + wIdhigh + wIdnuclear + wIdobs + wIdround + wSync*lam > 0,
  -wIdant + wIdhtone + wIdnuclear + wIdobs + wIdround > 0,
  -wIdant + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor*lam + wMutdor + 2*wNocoda*lam > 0,
  -wIdant + wIdlab + wMutdor > 0,
  -wIdant + wIdlab + wMutdor*lam + wMutdor > 0,
  -wIdant + wIdnuclear + wIdobs + wIdround > 0,
  -wIdant + wIdnuclear + wIdobs + wIdround + wMutdor + 2*wNocoda*lam > 0,
  -wIdant + wMutdor > 0,
  -wIdant + wMutdor*lam + wMutdor > 0,
  -wIdant - wIddor + wIdfront + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wMutdor > 0,
  -wIdant - wIddor + wIdfront + wIdglottal + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIdant - wIddor + wIdfront + wIdhigh + wIdhtone + wIdround + wMutdor > 0,
  -wIdant - wIddor + wIdfront + wIdhigh + wIdhtone + wIdround + wMutdor + wSync*lam > 0,
  -wIdant - wIddor + wIdfront + wIdhigh + wIdhtone + wIdround + wMutdor*lam + wMutdor > 0,
  -wIdant - wIddor + wIdfront + wIdhigh + wIdround + wMutdor > 0,
  -wIdant - wIddor + wIdfront + wIdhigh + wIdround + wMutdor + wSync*lam > 0,
  -wIdant - wIddor + wIdfront + wIdhigh + wIdround + wMutdor*lam + wMutdor + wSync*lam > 0,
  -wIdant - wIddor + wIdfront + wIdhtone + wIdnuclear + wIdround + wMutdor + 2*wNocoda*lam > 0,
  -wIdant - wIddor + wIdfront + wIdhtone + wIdround + wMutdor > 0,
  -wIdant - wIddor + wIdfront + wIdhtone + wIdround + wMutdor*lam + wMutdor > 0,
  -wIdant - wIddor + wIdfront + wIdnuclear + wIdround + wMutdor*lam + wMutdor + 2*wNocoda*lam > 0,
  -wIdant - wIddor + wIdfront + wIdround + wMutdor > 0,
  -wIdant - wIddor + wIdfront + wIdround + wMutdor*lam + wMutdor > 0,
  -wIdant - wIddor + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  -wIdant - wIddor + wIdglottal + wIdlab + wMutdor > 0,
  -wIdant - wIddor + wIdglottal + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  -wIdant - wIddor + wIdglottal + wMutdor > 0,
  -wIdant - wIddor + wIdhigh + wIdhtone + wMutdor > 0,
  -wIdant - wIddor + wIdhigh + wIdhtone + wMutdor + wSync*lam > 0,
  -wIdant - wIddor + wIdhigh + wMutdor > 0,
  -wIdant - wIddor + wIdhigh + wMutdor + wSync*lam > 0,
  -wIdant - wIddor + wIdhtone + wIdnuclear + wMutdor + wNocoda*lam > 0,
  -wIdant - wIddor + wIdhtone + wMutdor > 0,
  -wIdant - wIddor + wIdlab + wMutdor > 0,
  -wIdant - wIddor + wIdnas + wIdobs + wMutdor > 0,
  -wIdant - wIddor + wIdnuclear + wMutdor + 2*wNocoda*lam > 0,
  -wIdant - wIddor + wMax + wMutdor > 0,
  -wIdant - wIddor + wMax + wMutdor + wNocoda*lam > 0,
  -wIdant - wIddor + wMax + wMutdor - wNocoda > 0,
  -wIdant - wIddor + wMax - wNocoda > 0,
  -wIdant - wIddor - wIdseg + wMutdor > 0,
  -wIddor + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIddor + wIdfront + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  -wIddor + wIdglottal + wIdnas + wIdobs + wMutdor > 0,
  -wIddor + wIdglottal + wMutdor > 0,
  -wIddor + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor + 2*wNocoda*lam > 0,
  -wIddor + wIdlab + wIdnas + wIdobs + wMutdor > 0,
  -wIddor + wIdnas + wIdobs + wMutdor > 0,
  -wIddor + wIdnuclear + wIdobs + wIdround + wMutdor + 2*wNocoda*lam > 0,
  -wIddor + wMutdor > 0,
  wIdcont + wIdlab + wMutdor > 0,
  wIdcont + wIdnas + wIdobs > 0,
  wIdcont + wIdnas + wIdobs + wMutdor > 0,
  wIdcont + wMutant*lam > 0,
  wIdcont - wIddor + wIdfront + wIdhigh + wIdhtone + wIdnas + wIdnuclear + wMutdor - wNocoda > 0,
  wIdcont - wIddor + wIdfront + wIdhigh + wIdnas + wIdnuclear + wMutdor - wNocoda + wSync*lam > 0,
  wIdcont - wIddor + wIdfront + wIdhtone + wIdnas + wIdnuclear + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdhtone + wIdnas + wIdnuclear + wMutdor - wNocoda > 0,
  wIdcont - wIddor + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdnas + wIdnuclear + wMutdor + 2*wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdnas + wIdnuclear + wMutdor - wNocoda > 0,
  wIdcont - wIddor + wIdfront + wIdnas + wMutdor > 0,
  wIdcont - wIddor + wIdfront + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  wIdcont - wIddor + wIdglottal + wIdnas + wIdobs + wMutdor > 0,
  wIdcont - wIddor + wIdglottal + wMutdor > 0,
  wIdcont - wIddor + wIdhigh + wIdhtone + wIdnas + wIdnuclear + wIdround + wMutdor - wNocoda > 0,
  wIdcont - wIddor + wIdhigh + wIdnas + wIdnuclear + wIdround + wMutdor - wNocoda + wSync*lam > 0,
  wIdcont - wIddor + wIdhtone + wIdnas + wIdnuclear + wIdround + wMutdor + 2*wNocoda*lam > 0,
  wIdcont - wIddor + wIdhtone + wIdnas + wIdnuclear + wIdround + wMutdor - wNocoda > 0,
  wIdcont - wIddor + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor + 2*wNocoda*lam > 0,
  wIdcont - wIddor + wIdnas + wIdnuclear + wIdround + wMutdor + 2*wNocoda*lam > 0,
  wIdcont - wIddor + wIdnas + wIdnuclear + wIdround + wMutdor - wNocoda > 0,
  wIdcont - wIddor + wIdnuclear + wIdobs + wIdround + wMutdor + 2*wNocoda*lam > 0,
  wIdcont - wIddor + wMutdor > 0,
  wIdlab + wIdnas + wIdobs + wMutdor > 0,
  wIdlab + wMutdor > 0,
  wIdnas + wIdobs + wMutdor > 0,
  wMutant*lam > 0,
  -wIdant - wIddor + wIdseg - wNocoda > 0,
  wDep - wIdant - wIddor - wIdseg - wNocoda > 0,
  -wIddor + wIdfront + wIdglottal + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutdor > 0,
  -wIddor + wIdfront + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wMutdor + wSync*lam > 0,
  -wIddor + wIdfront + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wMutdor > 0,
  -wIddor + wIdfront + wIdglottal + wIdnuclear + wIdobs + wMutdor > 0,
  -wIddor + wIdfront + wIdglottal + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIddor + wIdfront + wIdglottal + wIdobs + wMutdor > 0,
  -wIddor + wIdfront + wIdhigh + wIdhtone + wIdround + wMutdor > 0,
  -wIddor + wIdfront + wIdhigh + wIdhtone + wIdround + wMutdor + wSync*lam > 0,
  -wIddor + wIdfront + wIdhigh + wIdhtone + wIdround + wMutdor - wSync > 0,
  -wIddor + wIdfront + wIdhigh + wIdhtone + wIdround + wMutdor*lam + wMutdor + wSync*lam > 0,
  -wIddor + wIdfront + wIdhigh + wIdnuclear + wIdround + wMutdor > 0,
  -wIddor + wIdfront + wIdhigh + wIdround + wMutdor > 0,
  -wIddor + wIdfront + wIdhigh + wIdround + wMutdor + wSync*lam > 0,
  -wIddor + wIdfront + wIdhigh + wIdround + wMutdor*lam + wMutdor > 0,
  -wIddor + wIdfront + wIdhtone + wIdnuclear + wIdround + wMutdor + wNocoda*lam > 0,
  -wIddor + wIdfront + wIdhtone + wIdnuclear + wIdround + wMutdor*lam + wMutdor + wNocoda*lam > 0,
  -wIddor + wIdfront + wIdhtone + wIdround + wMutdor > 0,
  -wIddor + wIdfront + wIdhtone + wIdround + wMutdor - wSync > 0,
  -wIddor + wIdfront + wIdhtone + wIdround + wMutdor*lam + wMutdor > 0,
  -wIddor + wIdfront + wIdround + wMutdor > 0,
  -wIddor + wIdfront + wIdround + wMutdor*lam + wMutdor > 0,
  -wIddor + wIdglottal + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIddor + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIddor + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wIdround + wMutdor + wSync*lam > 0,
  -wIddor + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIddor + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor*lam + wMutdor + wNocoda*lam > 0,
  -wIddor + wIdglottal + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIddor + wIdglottal + wMutdor > 0,
  -wIddor + wIdhigh + wIdhtone + wMutdor > 0,
  -wIddor + wIdhigh + wIdhtone + wMutdor + wSync*lam > 0,
  -wIddor + wIdhigh + wIdhtone + wMutdor - wSync > 0,
  -wIddor + wIdhigh + wMutdor > 0,
  -wIddor + wIdhigh + wMutdor + wSync*lam > 0,
  -wIddor + wIdhtone + wMutdor > 0,
  -wIddor + wIdhtone + wMutdor - wSync > 0,
  -wIddor + wIdlab + wMutdor > 0,
  -wIddor + wIdnuclear + wMutdor + 2*wNocoda*lam > 0,
  -wIddor + wMax + wMutdor > 0,
  -wIddor + wMax + wMutdor + wNocoda*lam > 0,
  -wIddor + wMax + wMutdor - wNocoda > 0,
  -wIddor + wMax + wMutdor - wSync > 0,
  -wIddor + wMax - wNocoda > 0,
  -wIddor - wIdseg + wMutdor > 0,
  wIdant + wIdcont + wIdlab > 0,
  wIdant + wIdcont + wIdlab + wMutant*lam > 0,
  wIdant + wIdcont + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdfront + wIdnas + wIdnuclear + wMutdor + 2*wNocoda*lam > 0,
  wIdant + wIdcont - wIddor + wIdfront + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  wIdant + wIdcont - wIddor + wIdglottal + wIdnas + wIdobs + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdglottal + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdhigh + wIdnas + wIdnuclear + wIdround + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdhigh + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdhtone + wIdnas + wIdnuclear + wIdround + wMutdor + wNocoda*lam > 0,
  wIdant + wIdcont - wIddor + wIdhtone + wIdnas + wIdnuclear + wIdround + wMutdor*lam + wMutdor + wNocoda*lam > 0,
  wIdant + wIdcont - wIddor + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  wIdant + wIdcont - wIddor + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor*lam + wMutdor + wNocoda*lam > 0,
  wIdant + wIdcont - wIddor + wMutdor > 0,
  wIdant + wIdlab + wIdnas + wIdobs > 0,
  wIdant + wIdlab + wMutant*lam > 0,
  wIdant + wIdnas + wIdobs + wMutdor > 0,
  wIdant + wMutdor > 0,
  wIdant - wIddor + wIdfront + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  wIdant - wIddor + wIdglottal + wMutdor > 0,
  wIdant - wIddor + wIdhigh + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  wIdant - wIddor + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  wIdant - wIddor + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor*lam + wMutdor + wNocoda*lam > 0,
  wIdant - wIddor + wIdnas + wIdobs + wMutdor > 0,
  wIdant - wIddor + wMutdor > 0,
  wIdcont + wIdfront + wIdhigh + wIdhtone + wIdlab + wIdnuclear + wIdobs > 0,
  wIdcont + wIdfront + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutdor - wNocoda > 0,
  wIdcont + wIdfront + wIdhigh + wIdlab + wIdnuclear + wIdobs + wSync*lam > 0,
  wIdcont + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutdor - wNocoda + wSync*lam > 0,
  wIdcont + wIdfront + wIdhtone + wIdlab + wIdnuclear + wIdobs > 0,
  wIdcont + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor - wNocoda > 0,
  wIdcont + wIdfront + wIdlab + wIdnuclear + wIdobs > 0,
  wIdcont + wIdfront + wIdlab + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  wIdcont + wIdfront + wIdlab + wIdobs > 0,
  wIdcont + wIdfront + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  wIdcont + wIdfront + wIdnuclear + wIdobs + wMutdor - wNocoda > 0,
  wIdcont + wIdfront + wIdobs + wMutdor > 0,
  wIdcont + wIdglottal + wIdlab > 0,
  wIdcont + wIdglottal + wIdlab + wMutdor > 0,
  wIdcont + wIdglottal + wMutdor > 0,
  wIdcont + wIdhigh + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdround > 0,
  wIdcont + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor - wNocoda > 0,
  wIdcont + wIdhigh + wIdlab + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  wIdcont + wIdhigh + wIdlab + wIdnuclear + wIdobs + wIdround + wSync*lam > 0,
  wIdcont + wIdhigh + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  wIdcont + wIdhigh + wIdnuclear + wIdobs + wIdround + wMutdor - wNocoda + wSync*lam > 0,
  wIdcont + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdround > 0,
  wIdcont + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  wIdcont + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdround + wMutdor*lam + wMutdor + wNocoda*lam > 0,
  wIdcont + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  wIdcont + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor - wNocoda > 0,
  wIdcont + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor*lam + wMutdor + wNocoda*lam > 0,
  wIdcont + wIdlab + wIdnuclear + wIdobs + wIdround > 0,
  wIdcont + wIdnuclear + wIdobs + wIdround + wMutdor - wNocoda > 0,
  wIdcont + wMutdor*lam + wMutdor > 0,
  wIdcont - wIddor + wIdfront + wIdglottal + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutdor > 0,
  wIdcont - wIddor + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutdor + wSync*lam > 0,
  wIdcont - wIddor + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor > 0,
  wIdcont - wIddor + wIdfront + wIdlab + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdnuclear + wIdobs + wMutdor > 0,
  wIdcont - wIddor + wIdfront + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdobs + wMutdor > 0,
  wIdcont - wIddor + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  wIdcont - wIddor + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  wIdcont - wIddor + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor*lam + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdglottal + wIdlab + wMutdor > 0,
  wIdcont - wIddor + wIdglottal + wMutdor > 0,
  wIdcont - wIddor + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  wIdcont - wIddor + wIdhigh + wIdlab + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  wIdcont - wIddor + wIdhigh + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  wIdcont - wIddor + wIdhigh + wIdnuclear + wIdobs + wIdround + wMutdor + wSync*lam > 0,
  wIdcont - wIddor + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdround + wMutdor*lam + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  wIdcont - wIddor + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor*lam + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdlab + wMutdor > 0,
  wIdcont - wIddor + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  wIdcont - wIddor + wMutdor > 0,
  wIdfront + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  wIdglottal + wIdlab > 0,
  wIdglottal + wMutdor > 0,
  wIdhigh + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor*lam + wMutdor + wNocoda*lam > 0,
  wIdlab > 0,
  wIdlab + wMutdor > 0,
  wIdlab + wMutdor*lam + wMutdor > 0,
  wMutdor > 0,
  wMutdor*(lam + 1) > 0,
  -wIddor + wIdseg - wNocoda - wSync > 0,
  wDep - wIddor - wIdseg - wNocoda - wSync > 0,
  -wIdseg + wMutant > 0,
  wIdant + wIdcont > 0,
  wIdant + wIdcont + wIddor + wIdlab + wMutdor*lam > 0,
  wIdant + wIdcont + wIddor + wIdnas + wIdobs + wMutant + wMutdor*lam > 0,
  wIdant + wIdcont + wIddor + wMutant > 0,
  wIdant + wIdcont + wIddor + wMutant + wMutdor*lam > 0,
  wIdant + wIdcont + wIddor + wMutdor*lam > 0,
  wIdant + wIdcont + wIdfront + wIdhigh + wIdhtone + wIdnas + wIdnuclear + wMutant > 0,
  wIdant + wIdcont + wIdfront + wIdhigh + wIdhtone + wIdnas + wIdnuclear + wMutant + wNocoda*lam > 0,
  wIdant + wIdcont + wIdfront + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutant > 0,
  wIdant + wIdcont + wIdfront + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutant + wNocoda*lam > 0,
  wIdant + wIdcont + wIdfront + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutant - wNocoda > 0,
  wIdant + wIdcont + wIdfront + wIdhigh + wIdnas + wIdnuclear + wMutant + 2*wNocoda*lam > 0,
  wIdant + wIdcont + wIdfront + wIdhigh + wIdnas + wIdnuclear + wMutant + wNocoda*lam > 0,
  wIdant + wIdcont + wIdfront + wIdhigh + wIdnas + wIdnuclear + wMutant + wSync*lam > 0,
  wIdant + wIdcont + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutant + 2*wNocoda*lam > 0,
  wIdant + wIdcont + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutant + wNocoda*lam > 0,
  wIdant + wIdcont + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutant + wSync*lam > 0,
  wIdant + wIdcont + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutant - wNocoda + wSync*lam > 0,
  wIdant + wIdcont + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutant*lam + wMutant + wNocoda*lam > 0,
  wIdant + wIdcont + wIdfront + wIdhtone + wIdnas + wIdnuclear + wMutant > 0,
  wIdant + wIdcont + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutant > 0,
  wIdant + wIdcont + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutant - wNocoda > 0,
  wIdant + wIdcont + wIdfront + wIdnas + wIdnuclear + wMutant > 0,
  wIdant + wIdcont + wIdfront + wIdnas + wIdnuclear + wMutant + 2*wNocoda*lam > 0,
  wIdant + wIdcont + wIdfront + wIdnas + wMutant > 0,
  wIdant + wIdcont + wIdfront + wIdnuclear + wIdobs + wMutant > 0,
  wIdant + wIdcont + wIdfront + wIdnuclear + wIdobs + wMutant + 2*wNocoda*lam > 0,
  wIdant + wIdcont + wIdfront + wIdnuclear + wIdobs + wMutant - wNocoda > 0,
  wIdant + wIdcont + wIdfront + wIdobs + wMutant > 0,
  wIdant + wIdcont + wIdglottal > 0,
  wIdant + wIdcont + wIdglottal + wIdnas + wIdobs + wMutant > 0,
  wIdant + wIdcont + wIdglottal + wIdnas + wIdobs + wMutant + wNocoda*lam > 0,
  wIdant + wIdcont + wIdglottal + wMutant > 0,
  wIdant + wIdcont + wIdglottal + wMutant*lam + wMutant + wNocoda*lam > 0,
  wIdant + wIdcont + wIdhigh + wIdhtone + wIdnas + wIdnuclear + wIdround + wMutant > 0,
  wIdant + wIdcont + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutant > 0,
  wIdant + wIdcont + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutant - wNocoda > 0,
  wIdant + wIdcont + wIdhigh + wIdnas + wIdnuclear + wIdround + wMutant + wSync*lam > 0,
  wIdant + wIdcont + wIdhigh + wIdnuclear + wIdobs + wIdround + wMutant + wSync*lam > 0,
  wIdant + wIdcont + wIdhigh + wIdnuclear + wIdobs + wIdround + wMutant - wNocoda + wSync*lam > 0,
  wIdant + wIdcont + wIdhtone + wIdnas + wIdnuclear + wIdround + wMutant > 0,
  wIdant + wIdcont + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutant > 0,
  wIdant + wIdcont + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutant - wNocoda > 0,
  wIdant + wIdcont + wIdlab > 0,
  wIdant + wIdcont + wIdlab + wMutant > 0,
  wIdant + wIdcont + wIdnas + wIdnuclear + wIdround + wMutant > 0,
  wIdant + wIdcont + wIdnuclear + wIdobs + wIdround + wMutant > 0,
  wIdant + wIdcont + wIdnuclear + wIdobs + wIdround + wMutant - wNocoda > 0,
  wIdant + wIddor + wIdlab + wIdnas + wIdobs + wMutant + wMutdor*lam > 0,
  wIdant + wIddor + wIdlab + wMutant > 0,
  wIdant + wIddor + wIdlab + wMutant + wMutdor*lam > 0,
  wIdant + wIddor + wIdnas + wIdobs + wMutant + wMutdor*lam > 0,
  wIdant + wIddor + wMutant > 0,
  wIdant + wIddor + wMutant + wMutdor*lam > 0,
  wIdant + wIddor + wMutdor*lam > 0,
  wIdant + wIdfront + wIdhigh + wIdhtone + wIdnuclear + wIdobs > 0,
  wIdant + wIdfront + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutant + wNocoda*lam > 0,
  wIdant + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutant + 2*wNocoda*lam > 0,
  wIdant + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutant + wNocoda*lam > 0,
  wIdant + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutant*lam + wMutant + wNocoda*lam > 0,
  wIdant + wIdfront + wIdhigh + wIdnuclear + wIdobs + wSync*lam > 0,
  wIdant + wIdfront + wIdhtone + wIdnuclear + wIdobs > 0,
  wIdant + wIdfront + wIdnuclear + wIdobs > 0,
  wIdant + wIdfront + wIdnuclear + wIdobs + wMutant + 2*wNocoda*lam > 0,
  wIdant + wIdfront + wIdobs > 0,
  wIdant + wIdglottal > 0,
  wIdant + wIdglottal + wIdnas + wIdobs + wMutant > 0,
  wIdant + wIdglottal + wMutant > 0,
  wIdant + wIdglottal + wMutant + wNocoda*lam > 0,
  wIdant + wIdglottal + wMutant*lam + wMutant + wNocoda*lam > 0,
  wIdant + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wIdround > 0,
  wIdant + wIdhigh + wIdnuclear + wIdobs + wIdround + wSync*lam > 0,
  wIdant + wIdhtone + wIdnuclear + wIdobs + wIdround > 0,
  wIdant + wIdlab + wIdnas + wIdobs + wMutant > 0,
  wIdant + wIdlab + wMutant > 0,
  wIdant + wIdnas + wIdobs + wMutant > 0,
  wIdant + wIdnuclear + wIdobs + wIdround > 0,
  wIdant + wMutant > 0,
  wIdcont + wIddor + wIdfront + wIdhigh + wIdhtone + wIdlab + wIdnuclear + wIdobs + wMutant + wMutdor*lam + wNocoda*lam > 0,
  wIdcont + wIddor + wIdfront + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutant + wMutdor*lam + wNocoda*lam > 0,
  wIdcont + wIddor + wIdfront + wIdhigh + wIdlab + wIdnuclear + wIdobs + wMutant + 2*wNocoda*lam > 0,
  wIdcont + wIddor + wIdfront + wIdhigh + wIdlab + wIdnuclear + wIdobs + wMutant + wMutdor*lam + wNocoda*lam > 0,
  wIdcont + wIddor + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutant + 2*wNocoda*lam > 0,
  wIdcont + wIddor + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutant + wMutdor*lam + wNocoda*lam > 0,
  wIdcont + wIddor + wIdfront + wIdlab + wIdnuclear + wIdobs + wMutant + wMutdor*lam + 2*wNocoda*lam > 0,
  wIdcont + wIddor + wIdfront + wIdnuclear + wIdobs + wMutant + wMutdor*lam + 2*wNocoda*lam > 0,
  wIdcont + wIddor + wIdglottal + wIdlab + wMutant + wMutdor*lam + wNocoda*lam > 0,
  wIdcont + wIddor + wIdglottal + wMutant + wMutdor*lam + wNocoda*lam > 0,
  wIdcont + wIddor + wIdlab + wMutant + wMutdor*lam > 0,
  wIdcont + wIdfront + wIdglottal + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutant + wNocoda*lam > 0,
  wIdcont + wIdfront + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wMutant > 0,
  wIdcont + wIdfront + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wMutant + wNocoda*lam > 0,
  wIdcont + wIdfront + wIdglottal + wIdnuclear + wIdobs + wMutant + wNocoda*lam > 0,
  wIdcont + wIdfront + wIdhigh + wIdhtone + wIdlab + wIdnuclear + wIdobs + wMutant > 0,
  wIdcont + wIdfront + wIdhigh + wIdhtone + wIdlab + wIdnuclear + wIdobs + wMutant + wNocoda*lam > 0,
  wIdcont + wIdfront + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutant + wNocoda*lam > 0,
  wIdcont + wIdfront + wIdhigh + wIdlab + wIdnuclear + wIdobs + wMutant + 2*wNocoda*lam > 0,
  wIdcont + wIdfront + wIdhigh + wIdlab + wIdnuclear + wIdobs + wMutant + wNocoda*lam > 0,
  wIdcont + wIdfront + wIdhigh + wIdlab + wIdnuclear + wIdobs + wMutant + wSync*lam > 0,
  wIdcont + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutant + 2*wNocoda*lam > 0,
  wIdcont + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutant + wNocoda*lam > 0,
  wIdcont + wIdfront + wIdhtone + wIdlab + wIdnuclear + wIdobs + wMutant > 0,
  wIdcont + wIdfront + wIdlab + wIdnuclear + wIdobs + wMutant > 0,
  wIdcont + wIdfront + wIdlab + wIdnuclear + wIdobs + wMutant + 2*wNocoda*lam > 0,
  wIdcont + wIdfront + wIdlab + wIdobs + wMutant > 0,
  wIdcont + wIdfront + wIdnuclear + wIdobs + wMutant + 2*wNocoda*lam > 0,
  wIdcont + wIdglottal + wIdlab + wMutant > 0,
  wIdcont + wIdglottal + wIdlab + wMutant + wNocoda*lam > 0,
  wIdcont + wIdglottal + wMutant + wNocoda*lam > 0,
  wIdcont + wIdhigh + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdround + wMutant > 0,
  wIdcont + wIdhigh + wIdlab + wIdnuclear + wIdobs + wIdround + wMutant + wSync*lam > 0,
  wIdcont + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdround + wMutant > 0,
  wIdcont + wIdlab + wIdnuclear + wIdobs + wIdround + wMutant > 0,
  wIdcont + wIdnas + wIdobs + wMutant > 0,
  wIdcont + wMutant > 0,
  wIddor + wIdfront + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutant + wMutdor*lam + wNocoda*lam > 0,
  wIddor + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutant + 2*wNocoda*lam > 0,
  wIddor + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutant + wMutdor*lam + wNocoda*lam > 0,
  wIddor + wIdfront + wIdnuclear + wIdobs + wMutant + wMutdor*lam + 2*wNocoda*lam > 0,
  wIddor + wIdglottal + wMutant + wMutdor*lam + wNocoda*lam > 0,
  wIddor + wIdlab + wMutant + wMutdor*lam > 0,
  wIddor + wMutant + wMutdor*lam > 0,
  wIdfront + wIdglottal + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutant > 0,
  wIdfront + wIdglottal + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutant + wNocoda*lam > 0,
  wIdfront + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wMutant > 0,
  wIdfront + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wMutant + wNocoda*lam > 0,
  wIdfront + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wMutant + wSync*lam > 0,
  wIdfront + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wMutant > 0,
  wIdfront + wIdglottal + wIdnuclear + wIdobs + wMutant > 0,
  wIdfront + wIdglottal + wIdnuclear + wIdobs + wMutant + wNocoda*lam > 0,
  wIdfront + wIdglottal + wIdobs + wMutant + wNocoda*lam > 0,
  wIdfront + wIdhigh + wIdhtone + wIdround + wMutant > 0,
  wIdfront + wIdhigh + wIdhtone + wIdround + wMutant - wSync > 0,
  wIdfront + wIdhigh + wIdround + wMutant > 0,
  wIdfront + wIdhigh + wIdround + wMutant + wSync*lam > 0,
  wIdfront + wIdhtone + wIdround + wMutant > 0,
  wIdfront + wIdhtone + wIdround + wMutant + wSync*lam > 0,
  wIdfront + wIdhtone + wIdround + wMutant - wSync > 0,
  wIdfront + wIdround + wMutant > 0,
  wIdglottal + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutant > 0,
  wIdglottal + wIdhigh + wIdnuclear + wIdobs + wIdround + wMutant + wSync*lam > 0,
  wIdglottal + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutant > 0,
  wIdglottal + wIdlab + wMutant > 0,
  wIdglottal + wIdnuclear + wIdobs + wIdround + wMutant > 0,
  wIdhigh + wIdhtone + wIdnuclear + wMutant + wNocoda*lam > 0,
  wIdhigh + wIdhtone + wMutant > 0,
  wIdhigh + wIdhtone + wMutant - wSync > 0,
  wIdhigh + wIdnuclear + wMutant + 2*wNocoda*lam > 0,
  wIdhigh + wIdnuclear + wMutant + wNocoda*lam > 0,
  wIdhigh + wMutant > 0,
  wIdhigh + wMutant + wSync*lam > 0,
  wIdhtone + wMutant > 0,
  wIdhtone + wMutant + wSync*lam > 0,
  wIdhtone + wMutant - wSync > 0,
  wIdlab + wMutant > 0,
  wIdnas + wIdobs + wMutant > 0,
  wIdnuclear + wMutant + 2*wNocoda*lam > 0,
  wMax + wMutant > 0,
  wMax + wMutant + wNocoda*lam > 0,
  wMax + wMutant + wNocoda*lam - wSync > 0,
  wMax + wMutant - wNocoda > 0,
  wMax + wMutant - wSync > 0,
  wMax - wNocoda > 0,
  wIdseg - wNocoda - 4*wSync > 0,
  wDep - wIdseg - wNocoda - 4*wSync > 0,
  wIdant + wIdcont + wIddor + wIdlab + wIdseg > 0,
  wIdant + wIdcont + wIddor + wIdnas + wIdobs + wIdseg > 0,
  wIdant + wIdcont + wIddor + wIdseg > 0,
  wIdant + wIdcont + wIdglottal + wIdnas + wIdobs + wIdseg > 0,
  wIdant + wIdcont + wIdglottal + wIdseg > 0,
  wIdant + wIdcont + wIdhtone + wIdnas + wIdnuclear + wIdround + wIdseg + 2*wNocoda*lam > 0,
  wIdant + wIdcont + wIdhtone + wIdnuclear + wIdobs + wIdround + wIdseg + 2*wNocoda*lam > 0,
  wIdant + wIdcont + wIdnas + wIdnuclear + wIdround + wIdseg > 0,
  wIdant + wIdcont + wIdnas + wIdnuclear + wIdround + wIdseg + wNocoda*lam > 0,
  wIdant + wIdcont + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIdant + wIdcont + wIdnuclear + wIdobs + wIdround + wIdseg + wNocoda*lam > 0,
  wIdant + wIddor + wIdlab + wIdnas + wIdobs + wIdseg > 0,
  wIdant + wIddor + wIdlab + wIdseg > 0,
  wIdant + wIddor + wIdseg > 0,
  wIdant + wIdglottal + wIdseg > 0,
  wIdant + wIdhtone + wIdnuclear + wIdobs + wIdround + wIdseg + 2*wNocoda*lam > 0,
  wIdant + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIdant + wIdnuclear + wIdobs + wIdround + wIdseg + wNocoda*lam > 0,
  wIdcont + wIddor + wIdfront + wIdhigh + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdseg > 0,
  wIdcont + wIddor + wIdfront + wIdhigh + wIdlab + wIdnuclear + wIdobs + wIdseg + wSync*lam > 0,
  wIdcont + wIddor + wIdfront + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdseg > 0,
  wIdcont + wIddor + wIdfront + wIdlab + wIdnuclear + wIdobs + wIdseg > 0,
  wIdcont + wIddor + wIdfront + wIdlab + wIdobs + wIdseg > 0,
  wIdcont + wIddor + wIdglottal + wIdlab + wIdseg > 0,
  wIdcont + wIddor + wIdglottal + wIdseg > 0,
  wIdcont + wIddor + wIdhigh + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIdcont + wIddor + wIdhigh + wIdlab + wIdnuclear + wIdobs + wIdround + wIdseg + wSync*lam > 0,
  wIdcont + wIddor + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIdcont + wIddor + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdround + wIdseg + 2*wNocoda*lam > 0,
  wIdcont + wIddor + wIdhtone + wIdnuclear + wIdobs + wIdround + wIdseg + 2*wNocoda*lam > 0,
  wIdcont + wIddor + wIdlab + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIdcont + wIddor + wIdlab + wIdnuclear + wIdobs + wIdround + wIdseg + wNocoda*lam > 0,
  wIdcont + wIddor + wIdlab + wIdseg > 0,
  wIdcont + wIddor + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIdcont + wIddor + wIdnuclear + wIdobs + wIdround + wIdseg + wNocoda*lam > 0,
  wIdcont + wIddor + wIdseg > 0,
  wIdcont + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wIdround + wIdseg + wNocoda*lam > 0,
  wIdcont + wIdglottal + wIdlab + wIdseg > 0,
  wIdcont + wIdglottal + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIdcont + wIdglottal + wIdseg > 0,
  wIdcont + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdround + wIdseg + 2*wNocoda*lam > 0,
  wIdcont + wIdhtone + wIdnuclear + wIdobs + wIdround + wIdseg + 2*wNocoda*lam > 0,
  wIdcont + wIdlab + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIdcont + wIdlab + wIdnuclear + wIdobs + wIdround + wIdseg + wNocoda*lam > 0,
  wIdcont + wIdlab + wIdseg > 0,
  wIdcont + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIdcont + wIdnuclear + wIdobs + wIdround + wIdseg + wNocoda*lam > 0,
  wIdcont + wIdseg > 0,
  wIddor + wIdfront + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wIdseg > 0,
  wIddor + wIdfront + wIdhigh + wIdnuclear + wIdobs + wIdseg + wSync*lam > 0,
  wIddor + wIdfront + wIdhtone + wIdnuclear + wIdobs + wIdseg > 0,
  wIddor + wIdfront + wIdnuclear + wIdobs + wIdseg > 0,
  wIddor + wIdfront + wIdobs + wIdseg > 0,
  wIddor + wIdglottal + wIdlab + wIdseg > 0,
  wIddor + wIdglottal + wIdseg > 0,
  wIddor + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIddor + wIdhigh + wIdnuclear + wIdobs + wIdround + wIdseg + wSync*lam > 0,
  wIddor + wIdhtone + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIddor + wIdhtone + wIdnuclear + wIdobs + wIdround + wIdseg + 2*wNocoda*lam > 0,
  wIddor + wIdlab + wIdseg > 0,
  wIddor + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIddor + wIdnuclear + wIdobs + wIdround + wIdseg + wNocoda*lam > 0,
  wIddor + wIdseg > 0,
  wIdfront + wIdglottal + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wIdseg + wMutdor*lam - wNocoda > 0,
  wIdfront + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wIdseg + wMutdor*lam - wNocoda + wSync*lam > 0,
  wIdfront + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wIdseg + wMutdor*lam - wNocoda > 0,
  wIdfront + wIdglottal + wIdnuclear + wIdobs + wIdseg + wMutdor*lam - wNocoda > 0,
  wIdfront + wIdglottal + wIdobs + wIdseg + wMutdor*lam > 0,
  wIdfront + wIdhigh + wIdhtone + wIdround + wIdseg > 0,
  wIdfront + wIdhigh + wIdhtone + wIdround + wIdseg + 2*wMutdor*lam + wSync*lam > 0,
  wIdfront + wIdhigh + wIdround + wIdseg + 2*wMutdor*lam > 0,
  wIdfront + wIdhigh + wIdround + wIdseg + wSync*lam > 0,
  wIdfront + wIdhtone + wIdnuclear + wIdround + wIdseg + wMutdor*lam + 2*wNocoda*lam > 0,
  wIdfront + wIdhtone + wIdround + wIdseg > 0,
  wIdfront + wIdhtone + wIdround + wIdseg + 2*wMutdor*lam > 0,
  wIdfront + wIdnuclear + wIdround + wIdseg > 0,
  wIdfront + wIdnuclear + wIdround + wIdseg + wNocoda*lam > 0,
  wIdfront + wIdround + wIdseg > 0,
  wIdfront + wIdround + wIdseg + 2*wMutdor*lam > 0,
  wIdglottal + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wIdround + wIdseg - wNocoda > 0,
  wIdglottal + wIdhigh + wIdnuclear + wIdobs + wIdround + wIdseg - wNocoda + wSync*lam > 0,
  wIdglottal + wIdhtone + wIdnuclear + wIdobs + wIdround + wIdseg + wNocoda*lam > 0,
  wIdglottal + wIdhtone + wIdnuclear + wIdobs + wIdround + wIdseg - wNocoda > 0,
  wIdglottal + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIdglottal + wIdnuclear + wIdobs + wIdround + wIdseg - wNocoda > 0,
  wIdhigh + wIdhtone + wIdseg > 0,
  wIdhigh + wIdhtone + wIdseg + wSync*lam > 0,
  wIdhigh + wIdseg > 0,
  wIdhigh + wIdseg + wSync*lam > 0,
  wIdhtone + wIdseg > 0,
  wIdlab + wIdseg > 0,
  wIdseg + wMax > 0,
  wIdseg + wMax + wNocoda*lam > 0,
  wIdseg + wMax - wNocoda > 0,
  2*wIdseg - wNocoda > 0,
  wDep - wNocoda > 0,
  wIdant + wIdcont + wIddor + wIdlab + wIdseg > 0,
  wIdant + wIdcont + wIddor + wIdnas + wIdobs + wIdseg > 0,
  wIdant + wIdcont + wIdfront + wIdhigh + wIdhtone + wIdnas + wIdnuclear + wIdseg > 0,
  wIdant + wIdcont + wIdfront + wIdhigh + wIdnas + wIdnuclear + wIdseg + wSync*lam > 0,
  wIdant + wIdcont + wIdfront + wIdhtone + wIdnas + wIdnuclear + wIdseg > 0,
  wIdant + wIdcont + wIdfront + wIdhtone + wIdnas + wIdnuclear + wIdseg + 2*wNocoda*lam > 0,
  wIdant + wIdcont + wIdfront + wIdhtone + wIdnuclear + wIdobs + wIdseg + 2*wNocoda*lam > 0,
  wIdant + wIdcont + wIdfront + wIdnas + wIdnuclear + wIdseg > 0,
  wIdant + wIdcont + wIdfront + wIdnas + wIdseg > 0,
  wIdant + wIdcont + wIdglottal + wIdnas + wIdobs + wIdseg > 0,
  wIdant + wIdcont + wIdglottal + wIdseg > 0,
  wIdant + wIdcont + wIdhigh + wIdhtone + wIdnas + wIdnuclear + wIdround + wIdseg > 0,
  wIdant + wIdcont + wIdhigh + wIdnas + wIdnuclear + wIdround + wIdseg + wSync*lam > 0,
  wIdant + wIdcont + wIdhtone + wIdnas + wIdnuclear + wIdround + wIdseg > 0,
  wIdant + wIdcont + wIdlab + wIdseg > 0,
  wIdant + wIdcont + wIdnas + wIdnuclear + wIdround + wIdseg > 0,
  wIdant + wIdcont + wIdnas + wIdnuclear + wIdround + wIdseg + wNocoda*lam > 0,
  wIdant + wIdcont + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIdant + wIdcont + wIdnuclear + wIdobs + wIdround + wIdseg + wNocoda*lam > 0,
  wIdant + wIddor + wIdlab + wIdnas + wIdobs + wIdseg > 0,
  wIdant + wIddor + wIdlab + wIdseg > 0,
  wIdant + wIddor + wIdnas + wIdobs + wIdseg > 0,
  wIdant + wIdfront + wIdhtone + wIdnuclear + wIdobs + wIdseg + 2*wNocoda*lam > 0,
  wIdant + wIdglottal + wIdnas + wIdobs + wIdseg > 0,
  wIdant + wIdglottal + wIdseg > 0,
  wIdant + wIdlab + wIdnas + wIdobs + wIdseg > 0,
  wIdant + wIdlab + wIdseg > 0,
  wIdant + wIdnas + wIdobs + wIdseg > 0,
  wIdant + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIdant + wIdnuclear + wIdobs + wIdround + wIdseg + wNocoda*lam > 0,
  wIdcont + wIddor + wIdfront + wIdhigh + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdseg > 0,
  wIdcont + wIddor + wIdfront + wIdhigh + wIdlab + wIdnuclear + wIdobs + wIdseg + wSync*lam > 0,
  wIdcont + wIddor + wIdfront + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdseg > 0,
  wIdcont + wIddor + wIdfront + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdseg + 2*wNocoda*lam > 0,
  wIdcont + wIddor + wIdfront + wIdhtone + wIdnuclear + wIdobs + wIdseg + 2*wNocoda*lam > 0,
  wIdcont + wIddor + wIdfront + wIdlab + wIdnuclear + wIdobs + wIdseg > 0,
  wIdcont + wIddor + wIdfront + wIdlab + wIdobs + wIdseg > 0,
  wIdcont + wIddor + wIdglottal + wIdlab + wIdseg > 0,
  wIdcont + wIddor + wIdglottal + wIdseg > 0,
  wIdcont + wIddor + wIdhigh + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIdcont + wIddor + wIdhigh + wIdlab + wIdnuclear + wIdobs + wIdround + wIdseg + wSync*lam > 0,
  wIdcont + wIddor + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIdcont + wIddor + wIdlab + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIdcont + wIddor + wIdlab + wIdnuclear + wIdobs + wIdround + wIdseg + wNocoda*lam > 0,
  wIdcont + wIddor + wIdlab + wIdseg + wMutdor*lam > 0,
  wIdcont + wIddor + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIdcont + wIddor + wIdnuclear + wIdobs + wIdround + wIdseg + wNocoda*lam > 0,
  wIdcont + wIdfront + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wIdseg + wNocoda*lam > 0,
  wIdcont + wIdfront + wIdhigh + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdseg + wMutdor*lam - wNocoda > 0,
  wIdcont + wIdfront + wIdhigh + wIdlab + wIdnuclear + wIdobs + wIdseg + wMutdor*lam - wNocoda + wSync*lam > 0,
  wIdcont + wIdfront + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdseg + 2*wNocoda*lam > 0,
  wIdcont + wIdfront + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdseg + wMutdor*lam - wNocoda > 0,
  wIdcont + wIdfront + wIdhtone + wIdnuclear + wIdobs + wIdseg + 2*wNocoda*lam > 0,
  wIdcont + wIdfront + wIdlab + wIdnuclear + wIdobs + wIdseg + wMutdor*lam - wNocoda > 0,
  wIdcont + wIdfront + wIdlab + wIdobs + wIdseg + wMutdor*lam > 0,
  wIdcont + wIdglottal + wIdlab + wIdseg > 0,
  wIdcont + wIdglottal + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIdcont + wIdglottal + wIdseg > 0,
  wIdcont + wIdhigh + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdround + wIdseg - wNocoda > 0,
  wIdcont + wIdhigh + wIdlab + wIdnuclear + wIdobs + wIdround + wIdseg - wNocoda + wSync*lam > 0,
  wIdcont + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdround + wIdseg - wNocoda > 0,
  wIdcont + wIdlab + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIdcont + wIdlab + wIdnuclear + wIdobs + wIdround + wIdseg + wNocoda*lam > 0,
  wIdcont + wIdlab + wIdnuclear + wIdobs + wIdround + wIdseg - wNocoda > 0,
  wIdcont + wIdlab + wIdseg > 0,
  wIdcont + wIdnas + wIdobs + wIdseg > 0,
  wIdcont + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIdcont + wIdnuclear + wIdobs + wIdround + wIdseg + wNocoda*lam > 0,
  wIdcont + wIdseg > 0,
  wIddor + wIdfront + wIdhtone + wIdnuclear + wIdobs + wIdseg + 2*wNocoda*lam > 0,
  wIddor + wIdglottal + wIdlab + wIdseg > 0,
  wIddor + wIdglottal + wIdseg > 0,
  wIddor + wIdlab + wIdseg > 0,
  wIddor + wIdlab + wIdseg + wMutdor*lam > 0,
  wIddor + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIddor + wIdnuclear + wIdobs + wIdround + wIdseg + wNocoda*lam > 0,
  wIddor + wIdseg > 0,
  wIddor + wIdseg + wMutdor*lam > 0,
  wIdfront + wIdglottal + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wIdseg > 0,
  wIdfront + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wIdseg + wSync*lam > 0,
  wIdfront + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wIdseg > 0,
  wIdfront + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wIdseg + wNocoda*lam > 0,
  wIdfront + wIdglottal + wIdnuclear + wIdobs + wIdseg > 0,
  wIdfront + wIdglottal + wIdobs + wIdseg > 0,
  wIdfront + wIdhigh + wIdhtone + wIdround + wIdseg > 0,
  wIdfront + wIdhigh + wIdhtone + wIdround + wIdseg + wMutdor*lam > 0,
  wIdfront + wIdhigh + wIdhtone + wIdround + wIdseg + wSync*lam > 0,
  wIdfront + wIdhigh + wIdround + wIdseg > 0,
  wIdfront + wIdhigh + wIdround + wIdseg + wMutdor*lam + wSync*lam > 0,
  wIdfront + wIdhigh + wIdround + wIdseg + wSync*lam > 0,
  wIdfront + wIdhtone + wIdround + wIdseg > 0,
  wIdfront + wIdhtone + wIdround + wIdseg + wMutdor*lam > 0,
  wIdfront + wIdnuclear + wIdround + wIdseg > 0,
  wIdfront + wIdnuclear + wIdround + wIdseg + wNocoda*lam > 0,
  wIdfront + wIdround + wIdseg > 0,
  wIdfront + wIdround + wIdseg + wMutdor*lam > 0,
  wIdglottal + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIdglottal + wIdhigh + wIdnuclear + wIdobs + wIdround + wIdseg + wSync*lam > 0,
  wIdglottal + wIdhtone + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIdglottal + wIdlab + wIdseg > 0,
  wIdglottal + wIdnuclear + wIdobs + wIdround + wIdseg > 0,
  wIdhigh + wIdhtone + wIdseg > 0,
  wIdhigh + wIdhtone + wIdseg + wSync*lam > 0,
  wIdhigh + wIdseg > 0,
  wIdhigh + wIdseg + wSync*lam > 0,
  wIdhtone + wIdnuclear + wIdseg + 2*wNocoda*lam > 0,
  wIdhtone + wIdseg > 0,
  wIdlab + wIdseg > 0,
  wIdnas + wIdobs + wIdseg > 0,
  wIdseg + wMax > 0,
  wIdseg + wMax + wMutdor*lam - wNocoda > 0,
  wIdseg + wMax + wNocoda*lam > 0,
  wIdseg + wMax - wNocoda > 0,
  2*wIdseg - wNocoda > 0,
  wDep - wNocoda > 0,
  -wIdant + wIdcont > 0,
  -wIdant + wIdcont + wIdfront + wIdhigh + wIdhtone + wIdlab + wIdnuclear + wIdobs + wMutdor*lam + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdcont + wIdfront + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutdor*lam + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdcont + wIdfront + wIdhigh + wIdlab + wIdnuclear + wIdobs + wMutdor*lam + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdcont + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutdor*lam + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdcont + wIdfront + wIdhtone + wIdlab + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdcont + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdcont + wIdfront + wIdlab + wIdnuclear + wIdobs + wMutdor*lam + wMutdor + 2*wNocoda*lam > 0,
  -wIdant + wIdcont + wIdfront + wIdnuclear + wIdobs + wMutdor*lam + wMutdor + 2*wNocoda*lam > 0,
  -wIdant + wIdcont + wIdglottal > 0,
  -wIdant + wIdcont + wIdglottal + wIdlab + wMutdor*lam + wMutdor > 0,
  -wIdant + wIdcont + wIdglottal + wMutdor > 0,
  -wIdant + wIdcont + wIdglottal + wMutdor*lam + wMutdor > 0,
  -wIdant + wIdcont + wIdlab > 0,
  -wIdant + wIdcont + wMutdor*lam + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdglottal + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdglottal + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wMutdor + wSync*lam > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdglottal + wIdnuclear + wIdobs + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdglottal + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdglottal + wIdobs + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdhigh + wIdhtone + wIdlab + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdhigh + wIdlab + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutdor + wSync*lam > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdhtone + wIdlab + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdlab + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdnuclear + wIdobs + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  -wIdant + wIdcont - wIddor + wIdfront + wIdobs + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdglottal + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wIdround + wMutdor + wSync*lam > 0,
  -wIdant + wIdcont - wIddor + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdglottal + wIdlab + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdglottal + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdglottal + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdhigh + wIdnuclear + wIdobs + wIdround + wMutdor + wSync*lam > 0,
  -wIdant + wIdcont - wIddor + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdlab + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIdant + wIdcont - wIddor + wMutdor > 0,
  -wIdant + wIdfront + wIdhigh + wIdhtone + wIdnuclear + wIdobs > 0,
  -wIdant + wIdfront + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutdor*lam + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutdor*lam + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdfront + wIdhigh + wIdnuclear + wIdobs + wSync*lam > 0,
  -wIdant + wIdfront + wIdhtone + wIdnuclear + wIdobs > 0,
  -wIdant + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIdant + wIdfront + wIdnuclear + wIdobs > 0,
  -wIdant + wIdfront + wIdnuclear + wIdobs + wMutdor*lam + wMutdor + 2*wNocoda*lam > 0,
  -wIdant + wIdfront + wIdobs > 0,
  -wIdant + wIdglottal > 0,
  -wIdant + wIdglottal + wIdlab + wMutdor > 0,
  -wIdant + wIdglottal + wMutdor > 0,
  -wIdant + wIdglottal + wMutdor*lam + wMutdor > 0,
  -wIdant + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wIdround > 0,
  -wIdant + wIdhigh + wIdnuclear + wIdobs + wIdround + wSync*lam > 0,
  -wIdant + wIdhtone + wIdnuclear + wIdobs + wIdround > 0,
  -wIdant + wIdlab + wMutdor*lam + wMutdor > 0,
  -wIdant + wIdnuclear + wIdobs + wIdround > 0,
  -wIdant + wMutdor*lam + wMutdor > 0,
  -wIdant - wIddor + wIdfront + wIdglottal + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutdor > 0,
  -wIdant - wIddor + wIdfront + wIdglottal + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIdant - wIddor + wIdfront + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wMutdor > 0,
  -wIdant - wIddor + wIdfront + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wMutdor + wSync*lam > 0,
  -wIdant - wIddor + wIdfront + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wMutdor > 0,
  -wIdant - wIddor + wIdfront + wIdglottal + wIdnuclear + wIdobs + wMutdor > 0,
  -wIdant - wIddor + wIdfront + wIdglottal + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIdant - wIddor + wIdfront + wIdglottal + wIdobs + wMutdor > 0,
  -wIdant - wIddor + wIdfront + wIdhigh + wIdhtone + wIdround + wMutdor > 0,
  -wIdant - wIddor + wIdfront + wIdhigh + wIdhtone + wIdround + wMutdor + wSync*lam > 0,
  -wIdant - wIddor + wIdfront + wIdhigh + wIdhtone + wIdround + wMutdor - wSync > 0,
  -wIdant - wIddor + wIdfront + wIdhigh + wIdround + wMutdor > 0,
  -wIdant - wIddor + wIdfront + wIdhigh + wIdround + wMutdor + wSync*lam > 0,
  -wIdant - wIddor + wIdfront + wIdhtone + wIdround + wMutdor > 0,
  -wIdant - wIddor + wIdfront + wIdhtone + wIdround + wMutdor + wSync*lam > 0,
  -wIdant - wIddor + wIdfront + wIdhtone + wIdround + wMutdor - wSync > 0,
  -wIdant - wIddor + wIdfront + wIdround + wMutdor > 0,
  -wIdant - wIddor + wIdglottal + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIdant - wIddor + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wIdround + wMutdor + wSync*lam > 0,
  -wIdant - wIddor + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIdant - wIddor + wIdglottal + wIdlab + wMutdor > 0,
  -wIdant - wIddor + wIdglottal + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIdant - wIddor + wIdglottal + wMutdor > 0,
  -wIdant - wIddor + wIdhigh + wIdhtone + wIdnuclear + wMutdor + wNocoda*lam > 0,
  -wIdant - wIddor + wIdhigh + wIdhtone + wMutdor > 0,
  -wIdant - wIddor + wIdhigh + wIdhtone + wMutdor + wSync*lam > 0,
  -wIdant - wIddor + wIdhigh + wIdhtone + wMutdor - wSync > 0,
  -wIdant - wIddor + wIdhigh + wIdnuclear + wMutdor + wNocoda*lam > 0,
  -wIdant - wIddor + wIdhigh + wMutdor > 0,
  -wIdant - wIddor + wIdhigh + wMutdor + wSync*lam > 0,
  -wIdant - wIddor + wIdhtone + wIdnuclear + wMutdor + wNocoda*lam > 0,
  -wIdant - wIddor + wIdhtone + wMutdor > 0,
  -wIdant - wIddor + wIdhtone + wMutdor + wSync*lam > 0,
  -wIdant - wIddor + wIdhtone + wMutdor - wSync > 0,
  -wIdant - wIddor + wIdlab + wMutdor > 0,
  -wIdant - wIddor + wIdnuclear + wMutdor + 2*wNocoda*lam > 0,
  -wIdant - wIddor + wMax > 0,
  -wIdant - wIddor + wMax + wMutdor > 0,
  -wIdant - wIddor + wMax + wMutdor + wNocoda*lam > 0,
  -wIdant - wIddor + wMax + wMutdor - wSync > 0,
  -wIdant - wIddor - wIdseg + wMutdor > 0,
  -wIddor + wIdfront + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIddor + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIddor + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIddor + wIdfront + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  -wIddor + wIdglottal + wIdnas + wIdobs + wMutdor > 0,
  -wIddor + wIdglottal + wMutdor > 0,
  -wIddor + wIdnas + wIdobs + wMutdor > 0,
  -wIddor + wMutdor > 0,
  wIdcont + wIdnas + wIdobs > 0,
  wIdcont + wMutant*lam > 0,
  wIdcont - wIddor + wIdfront + wIdhigh + wIdhtone + wIdnas + wIdnuclear + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdhigh + wIdnas + wIdnuclear + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdhtone + wIdnas + wIdnuclear + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdnas + wIdnuclear + wMutdor + 2*wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  wIdcont - wIddor + wIdglottal + wIdnas + wIdobs + wMutdor > 0,
  wIdcont - wIddor + wIdglottal + wMutdor > 0,
  wIdcont - wIddor + wMutdor > 0,
  wMutant*lam > 0,
  -wIdant - wIddor + wIdseg - 2*wSync > 0,
  wDep - wIdant - wIddor - wIdseg - 2*wSync > 0,
  -wIddor + wIdfront + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wMutdor > 0,
  -wIddor + wIdfront + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIddor + wIdfront + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wMutdor > 0,
  -wIddor + wIdfront + wIdglottal + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIddor + wIdfront + wIdhigh + wIdhtone + wIdround + wMutdor > 0,
  -wIddor + wIdfront + wIdhigh + wIdhtone + wIdround + wMutdor + wSync*lam > 0,
  -wIddor + wIdfront + wIdhigh + wIdhtone + wIdround + wMutdor - wSync > 0,
  -wIddor + wIdfront + wIdhigh + wIdround + wMutdor > 0,
  -wIddor + wIdfront + wIdhigh + wIdround + wMutdor + wSync*lam > 0,
  -wIddor + wIdfront + wIdhtone + wIdround + wMutdor > 0,
  -wIddor + wIdfront + wIdhtone + wIdround + wMutdor - wSync > 0,
  -wIddor + wIdfront + wIdround + wMutdor > 0,
  -wIddor + wIdhigh + wIdhtone + wMutdor > 0,
  -wIddor + wIdhigh + wIdhtone + wMutdor + wSync*lam > 0,
  -wIddor + wIdhigh + wIdhtone + wMutdor - wSync > 0,
  -wIddor + wIdhigh + wIdnuclear + wMutdor > 0,
  -wIddor + wIdhigh + wIdnuclear + wMutdor + wNocoda*lam > 0,
  -wIddor + wIdhigh + wMutdor > 0,
  -wIddor + wIdhigh + wMutdor + wSync*lam > 0,
  -wIddor + wIdhtone + wIdnuclear + wMutdor + wNocoda*lam > 0,
  -wIddor + wIdhtone + wMutdor > 0,
  -wIddor + wIdhtone + wMutdor - wSync > 0,
  -wIddor + wIdlab + wMutdor > 0,
  -wIddor + wIdnas + wIdobs + wMutdor > 0,
  -wIddor + wIdnuclear + wMutdor + 2*wNocoda*lam > 0,
  -wIddor + wMax > 0,
  -wIddor + wMax + wMutdor > 0,
  -wIddor + wMax + wMutdor + wNocoda*lam > 0,
  -wIddor + wMax + wMutdor - wSync > 0,
  -wIddor - wIdseg + wMutdor > 0,
  wIdant + wIdcont > 0,
  wIdant + wIdcont + wMutant*lam > 0,
  wIdant + wIdcont + wMutdor*lam + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdfront + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdfront + wIdhigh + wIdnas + wIdnuclear + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdfront + wIdhigh + wIdnas + wIdnuclear + wMutdor + wNocoda*lam > 0,
  wIdant + wIdcont - wIddor + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  wIdant + wIdcont - wIddor + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutdor + wSync*lam > 0,
  wIdant + wIdcont - wIddor + wIdfront + wIdhtone + wIdnas + wIdnuclear + wMutdor + wNocoda*lam > 0,
  wIdant + wIdcont - wIddor + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  wIdant + wIdcont - wIddor + wIdfront + wIdnas + wIdnuclear + wMutdor + 2*wNocoda*lam > 0,
  wIdant + wIdcont - wIddor + wIdfront + wIdnuclear + wIdobs + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdfront + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  wIdant + wIdcont - wIddor + wIdfront + wIdobs + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdglottal + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdhigh + wIdnuclear + wIdobs + wIdround + wMutdor + wSync*lam > 0,
  wIdant + wIdcont - wIddor + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  wIdant + wIdlab + wMutdor*lam + wMutdor > 0,
  wIdant + wIdnas + wIdobs > 0,
  wIdant + wMutant*lam > 0,
  wIdant + wMutdor*lam + wMutdor > 0,
  wIdant - wIddor + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutdor > 0,
  wIdant - wIddor + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  wIdant - wIddor + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  wIdant - wIddor + wIdfront + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  wIdant - wIddor + wIdglottal + wMutdor > 0,
  wIdant - wIddor + wIdlab + wMutdor > 0,
  wIdant - wIddor + wMutdor > 0,
  wIdcont + wIdfront + wIdhigh + wIdhtone + wIdnuclear + wIdobs > 0,
  wIdcont + wIdfront + wIdhigh + wIdlab + wIdnuclear + wIdobs + wMutdor > 0,
  wIdcont + wIdfront + wIdhigh + wIdlab + wIdnuclear + wIdobs + wMutdor*lam + wMutdor + wNocoda*lam > 0,
  wIdcont + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutdor > 0,
  wIdcont + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutdor*lam + wMutdor + wNocoda*lam > 0,
  wIdcont + wIdfront + wIdhigh + wIdnuclear + wIdobs + wSync*lam > 0,
  wIdcont + wIdfront + wIdhtone + wIdlab + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  wIdcont + wIdfront + wIdhtone + wIdnuclear + wIdobs > 0,
  wIdcont + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  wIdcont + wIdfront + wIdlab + wIdnuclear + wIdobs + wMutdor*lam + wMutdor + 2*wNocoda*lam > 0,
  wIdcont + wIdfront + wIdnuclear + wIdobs > 0,
  wIdcont + wIdfront + wIdnuclear + wIdobs + wMutdor*lam + wMutdor + 2*wNocoda*lam > 0,
  wIdcont + wIdfront + wIdobs > 0,
  wIdcont + wIdglottal > 0,
  wIdcont + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wIdround > 0,
  wIdcont + wIdhigh + wIdnuclear + wIdobs + wIdround + wSync*lam > 0,
  wIdcont + wIdhtone + wIdnuclear + wIdobs + wIdround > 0,
  wIdcont + wIdnuclear + wIdobs + wIdround > 0,
  wIdcont - wIddor + wIdfront + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wMutdor > 0,
  wIdcont - wIddor + wIdfront + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wMutdor > 0,
  wIdcont - wIddor + wIdfront + wIdglottal + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdhigh + wIdlab + wIdnuclear + wIdobs + wMutdor > 0,
  wIdcont - wIddor + wIdfront + wIdhigh + wIdlab + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutdor > 0,
  wIdcont - wIddor + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdhtone + wIdlab + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdlab + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  wIdcont - wIddor + wMutdor > 0,
  wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutdor > 0,
  wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutdor*lam + wMutdor + wNocoda*lam > 0,
  wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  wIdfront + wIdnuclear + wIdobs + wMutdor*lam + wMutdor + 2*wNocoda*lam > 0,
  wIdglottal > 0,
  wIdlab > 0,
  -wIddor + wIdseg - 2*wSync > 0,
  wDep - wIddor - wIdseg - 2*wSync > 0,
  -wIddor + wIdfront + wIdglottal + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutdor > 0,
  -wIddor + wIdfront + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wMutdor + wSync*lam > 0,
  -wIddor + wIdfront + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wMutdor > 0,
  -wIddor + wIdfront + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIddor + wIdfront + wIdglottal + wIdnuclear + wIdobs + wMutdor > 0,
  -wIddor + wIdfront + wIdglottal + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  -wIddor + wIdfront + wIdglottal + wIdobs + wMutdor > 0,
  -wIddor + wIdfront + wIdhigh + wIdhtone + wIdround + wMutdor > 0,
  -wIddor + wIdfront + wIdhigh + wIdhtone + wIdround + wMutdor + wSync*lam > 0,
  -wIddor + wIdfront + wIdhigh + wIdround + wMutdor > 0,
  -wIddor + wIdfront + wIdhigh + wIdround + wMutdor + wSync*lam > 0,
  -wIddor + wIdfront + wIdhtone + wIdnuclear + wIdround + wMutdor + wNocoda*lam > 0,
  -wIddor + wIdfront + wIdhtone + wIdround + wMutdor > 0,
  -wIddor + wIdfront + wIdnuclear + wIdround + wMutdor + wNocoda*lam > 0,
  -wIddor + wIdfront + wIdround + wMutdor > 0,
  -wIddor + wIdglottal + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIddor + wIdglottal + wIdhigh + wIdnuclear + wIdobs + wIdround + wMutdor + wSync*lam > 0,
  -wIddor + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIddor + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  -wIddor + wIdglottal + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  -wIddor + wIdhigh + wIdhtone + wMutdor > 0,
  -wIddor + wIdhigh + wIdhtone + wMutdor + wSync*lam > 0,
  -wIddor + wIdhigh + wMutdor > 0,
  -wIddor + wIdhigh + wMutdor + wSync*lam > 0,
  -wIddor + wIdhtone + wIdnuclear + wMutdor + 2*wNocoda*lam > 0,
  -wIddor + wIdhtone + wMutdor > 0,
  -wIddor + wIdlab + wMutdor > 0,
  -wIddor + wIdnas + wIdobs + wMutdor > 0,
  -wIddor + wIdnuclear + wMutdor + 2*wNocoda*lam > 0,
  -wIddor + wMax > 0,
  -wIddor + wMax + wMutdor > 0,
  -wIddor + wMax + wMutdor + wNocoda*lam > 0,
  -wIddor + wMutdor > 0,
  -wIddor - wIdseg + wMutdor > 0,
  wIdant + wIdcont + wIdlab > 0,
  wIdant + wIdcont + wIdlab + wMutant*lam > 0,
  wIdant + wIdcont + wIdlab + wMutdor*lam + wMutdor > 0,
  wIdant + wIdcont + wIdnas + wIdobs + wMutdor > 0,
  wIdant + wIdcont + wMutdor*lam + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdfront + wIdhigh + wIdhtone + wIdnas + wIdnuclear + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdfront + wIdhigh + wIdnas + wIdnuclear + wMutdor + wSync*lam > 0,
  wIdant + wIdcont - wIddor + wIdfront + wIdhtone + wIdnas + wIdnuclear + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdfront + wIdhtone + wIdnas + wIdnuclear + wMutdor + 2*wNocoda*lam > 0,
  wIdant + wIdcont - wIddor + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  wIdant + wIdcont - wIddor + wIdfront + wIdnas + wIdnuclear + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdfront + wIdnas + wIdnuclear + wMutdor + 2*wNocoda*lam > 0,
  wIdant + wIdcont - wIddor + wIdfront + wIdnas + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdfront + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  wIdant + wIdcont - wIddor + wIdglottal + wIdnas + wIdobs + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdglottal + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdhigh + wIdhtone + wIdnas + wIdnuclear + wIdround + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdhigh + wIdnas + wIdnuclear + wIdround + wMutdor + wSync*lam > 0,
  wIdant + wIdcont - wIddor + wIdhtone + wIdnas + wIdnuclear + wIdround + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdhtone + wIdnas + wIdnuclear + wIdround + wMutdor + wNocoda*lam > 0,
  wIdant + wIdcont - wIddor + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  wIdant + wIdcont - wIddor + wIdlab + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdnas + wIdnuclear + wIdround + wMutdor > 0,
  wIdant + wIdcont - wIddor + wIdnas + wIdnuclear + wIdround + wMutdor + wNocoda*lam > 0,
  wIdant + wIdcont - wIddor + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  wIdant + wIdcont - wIddor + wMutdor > 0,
  wIdant + wIdlab + wIdnas + wIdobs > 0,
  wIdant + wIdlab + wIdnas + wIdobs + wMutdor > 0,
  wIdant + wIdlab + wMutant*lam > 0,
  wIdant + wIdnas + wIdobs + wMutdor > 0,
  wIdant + wMutdor*lam + wMutdor > 0,
  wIdant - wIddor + wIdfront + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wMutdor > 0,
  wIdant - wIddor + wIdfront + wIdhigh + wIdnuclear + wIdobs + wMutdor + wSync*lam > 0,
  wIdant - wIddor + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor > 0,
  wIdant - wIddor + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  wIdant - wIddor + wIdfront + wIdnuclear + wIdobs + wMutdor > 0,
  wIdant - wIddor + wIdfront + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  wIdant - wIddor + wIdfront + wIdobs + wMutdor > 0,
  wIdant - wIddor + wIdglottal + wIdnas + wIdobs + wMutdor > 0,
  wIdant - wIddor + wIdglottal + wMutdor > 0,
  wIdant - wIddor + wIdhigh + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  wIdant - wIddor + wIdhigh + wIdnuclear + wIdobs + wIdround + wMutdor + wSync*lam > 0,
  wIdant - wIddor + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  wIdant - wIddor + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  wIdant - wIddor + wIdlab + wIdnas + wIdobs + wMutdor > 0,
  wIdant - wIddor + wIdnas + wIdobs + wMutdor > 0,
  wIdant - wIddor + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  wIdant - wIddor + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  wIdcont + wIdfront + wIdhigh + wIdhtone + wIdlab + wIdnuclear + wIdobs > 0,
  wIdcont + wIdfront + wIdhigh + wIdlab + wIdnuclear + wIdobs + wSync*lam > 0,
  wIdcont + wIdfront + wIdhtone + wIdlab + wIdnuclear + wIdobs > 0,
  wIdcont + wIdfront + wIdhtone + wIdlab + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  wIdcont + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  wIdcont + wIdfront + wIdlab + wIdnuclear + wIdobs > 0,
  wIdcont + wIdfront + wIdlab + wIdnuclear + wIdobs + wMutdor*lam + wMutdor + 2*wNocoda*lam > 0,
  wIdcont + wIdfront + wIdlab + wIdobs > 0,
  wIdcont + wIdfront + wIdnuclear + wIdobs + wMutdor*lam + wMutdor + 2*wNocoda*lam > 0,
  wIdcont + wIdglottal + wIdlab > 0,
  wIdcont + wIdglottal + wIdlab + wMutdor > 0,
  wIdcont + wIdglottal + wMutdor > 0,
  wIdcont + wIdhigh + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdround > 0,
  wIdcont + wIdhigh + wIdlab + wIdnuclear + wIdobs + wIdround + wSync*lam > 0,
  wIdcont + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdround > 0,
  wIdcont + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  wIdcont + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  wIdcont + wIdlab + wIdnuclear + wIdobs + wIdround > 0,
  wIdcont + wIdlab + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  wIdcont + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdglottal + wIdnuclear + wIdobs + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdhtone + wIdlab + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdlab + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  wIdcont - wIddor + wIdfront + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  wIdcont - wIddor + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  wIdcont - wIddor + wIdglottal + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdglottal + wIdlab + wMutdor > 0,
  wIdcont - wIddor + wIdglottal + wIdnuclear + wIdobs + wIdround + wMutdor > 0,
  wIdcont - wIddor + wIdglottal + wMutdor > 0,
  wIdcont - wIddor + wIdhtone + wIdlab + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdlab + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wIdlab + wMutdor > 0,
  wIdcont - wIddor + wIdnas + wIdobs + wMutdor > 0,
  wIdcont - wIddor + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  wIdcont - wIddor + wMutdor > 0,
  wIdfront + wIdhtone + wIdnuclear + wIdobs + wMutdor + 2*wNocoda*lam > 0,
  wIdfront + wIdnuclear + wIdobs + wMutdor*lam + wMutdor + 2*wNocoda*lam > 0,
  wIdglottal + wIdlab > 0,
  wIdglottal + wMutdor > 0,
  wIdhtone + wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  wIdlab > 0,
  wIdnuclear + wIdobs + wIdround + wMutdor + wNocoda*lam > 0,
  -wIddor + wIdseg > 0,
  wDep - wIddor - wIdseg > 0
];
wsub = {wDep -> 10, wIdant -> 1, wIdcont -> 2, wIddor -> 1, wIdfront -> 1, wIdglottal -> 2, wIdhigh -> 1, wIdhtone -> 1, wIdlab -> 1, wIdnas -> 1, wIdnuclear -> 3, wIdobs -> 1, wIdround -> 1, wIdseg -> 5, wMax -> 10, wMutant -> 8, wMutdor -> 8, wNocoda -> 2, wSync -> 0, lam -> 1/8};
control = wMutdor*lam < wIddor + wIdseg;
wv = DeleteCases[vars, lam];
root = NestWhile[ParentDirectory, DirectoryName[$InputFileName], !(DirectoryQ[FileNameJoin[{#, "python"}]] && DirectoryQ[FileNameJoin[{#, "wolfram"}]]) &, 1, 8];
outdir = FileNameJoin[{root, "results", "requirements", "wolfram"}];
If[!DirectoryQ[outdir], CreateDirectory[outdir, CreateIntermediateDirectories -> True]];
res = <|"witness_satisfies_all" -> ToString[And @@ (List @@ cons /. wsub), InputForm], "feasible_lambda_with_control" -> ToString[Reduce[Exists[Evaluate[wv], nonneg && cons && control] && lam >= 0, lam, Reals], InputForm], "feasible_lambda_without_control" -> ToString[Reduce[Exists[Evaluate[wv], nonneg && cons] && lam >= 0, lam, Reals], InputForm]|>;
Export[FileNameJoin[{outdir, "transient_environments_region.json"}], res, "JSON"];
Print[res];