GRAMMAR = {'source': 'appendix G, the Gua product and its nine readers: alphabet, feature inventory and schemata',
 'alphabet': ['∅', 'a', 'ɜ', 'ɛ', 'e', 'ɪ', 'i', 'ɔ', 'o', 'ʊ', 'u', 'j', 'w'],
 'inventory': {'∅': {'nuclear': False, 'present': False, 'atr': None, 'quality': None, 'high': False},
               'a': {'nuclear': True, 'present': True, 'atr': False, 'quality': 0, 'high': False},
               'ɜ': {'nuclear': True, 'present': True, 'atr': True, 'quality': 0, 'high': False},
               'ɛ': {'nuclear': True, 'present': True, 'atr': False, 'quality': 1, 'high': False},
               'e': {'nuclear': True, 'present': True, 'atr': True, 'quality': 1, 'high': False},
               'ɪ': {'nuclear': True, 'present': True, 'atr': False, 'quality': 2, 'high': True},
               'i': {'nuclear': True, 'present': True, 'atr': True, 'quality': 2, 'high': True},
               'ɔ': {'nuclear': True, 'present': True, 'atr': False, 'quality': 3, 'high': False},
               'o': {'nuclear': True, 'present': True, 'atr': True, 'quality': 3, 'high': False},
               'ʊ': {'nuclear': True, 'present': True, 'atr': False, 'quality': 4, 'high': True},
               'u': {'nuclear': True, 'present': True, 'atr': True, 'quality': 4, 'high': True},
               'j': {'nuclear': False, 'present': True, 'atr': None, 'quality': 2, 'high': False},
               'w': {'nuclear': False, 'present': True, 'atr': None, 'quality': 4, 'high': False}},
 'types': ['MAX', 'IDENT_ATR', 'IDENT_QUALITY', 'IDENT_NUC', 'H', 'A', 'GL', 'D', 'INITIAL_FEATURE']}

INPUTS_SELECTION = [{'id': 'G34a',
  'phase': 'opaque',
  'slots': [{'word': 0, 'phone': 'a'},
            {'word': 0, 'phone': 'h'},
            {'word': 0, 'phone': 'ɛ'},
            {'word': 1, 'phone': 't'},
            {'word': 1, 'phone': 'e'},
            {'word': 2, 'phone': 'ɔ'},
            {'word': 2, 'phone': 'k'},
            {'word': 2, 'phone': 'p'},
            {'word': 2, 'phone': 'ʊ'},
            {'word': 2, 'phone': 'k'},
            {'word': 2, 'phone': 'ɔ'}],
  'focal': [2, 4, 5],
  'phrases': [0, 0, 0]},
 {'id': 'G34b',
  'phase': 'opaque',
  'slots': [{'word': 0, 'phone': 'a'},
            {'word': 0, 'phone': 'f'},
            {'word': 0, 'phone': 'ɪ'},
            {'word': 1, 'phone': 's'},
            {'word': 1, 'phone': 'ɛ'},
            {'word': 2, 'phone': 'o'},
            {'word': 2, 'phone': 'h'},
            {'word': 2, 'phone': 'i'},
            {'word': 2, 'phone': 'l'},
            {'word': 2, 'phone': 'i'}],
  'focal': [2, 4, 5],
  'phrases': [0, 0, 0]},
 {'id': 'N7',
  'phase': 'opaque',
  'slots': [{'word': 0, 'phone': 'a'},
            {'word': 0, 'phone': 'tʃ'},
            {'word': 0, 'phone': 'ɪ'},
            {'word': 1, 'phone': 'j'},
            {'word': 1, 'phone': 'e'},
            {'word': 1, 'phone': 'l'},
            {'word': 1, 'phone': 'i'}],
  'focal': [2, 4],
  'phrases': [0, 0]},
 {'id': 'G37c',
  'phase': 'opaque',
  'slots': [{'word': 0, 'phone': 'ɔ'},
            {'word': 0, 'phone': 'tʃ'},
            {'word': 0, 'phone': 'ʊ'},
            {'word': 1, 'phone': 's'},
            {'word': 1, 'phone': 'ɛ'},
            {'word': 2, 'phone': 'i'},
            {'word': 2, 'phone': 'b'},
            {'word': 2, 'phone': 'i'},
            {'word': 2, 'phone': 'e'}],
  'focal': [2, 4, 5],
  'phrases': [0, 0, 0]},
 {'id': 'C24ei',
  'phase': 'control',
  'slots': [{'word': 0, 'phone': 'k'},
            {'word': 0, 'phone': 'p'},
            {'word': 0, 'phone': 'e'},
            {'word': 1, 'phone': 'i'},
            {'word': 1, 'phone': 's'},
            {'word': 1, 'phone': 'i'}],
  'focal': [2, 3],
  'phrases': [0, 0]}]

INPUTS_DELETION = [{'id': 'OR38',
  'phase': 'opaque',
  'slots': [{'word': 0, 'phone': 'a'},
            {'word': 0, 'phone': 'tʃ'},
            {'word': 0, 'phone': 'ɔ'},
            {'word': 1, 'phone': 's'},
            {'word': 1, 'phone': 'ɪ'},
            {'word': 2, 'phone': 'i'},
            {'word': 2, 'phone': 'k'},
            {'word': 2, 'phone': 'u'}],
  'focal': [2, 4, 5],
  'phrases': [0, 0, 0]},
 {'id': 'C21b',
  'phase': 'control',
  'slots': [{'word': 0, 'phone': 'w'},
            {'word': 0, 'phone': 'ʊ'},
            {'word': 0, 'phone': 's'},
            {'word': 0, 'phone': 'ʊ'},
            {'word': 1, 'phone': 'ɪ'},
            {'word': 1, 'phone': 's'},
            {'word': 1, 'phone': 'ɛ'}],
  'focal': [3, 4],
  'phrases': [0, 0]},
 {'id': 'C23UE',
  'phase': 'control',
  'slots': [{'word': 0, 'phone': 'w'},
            {'word': 0, 'phone': 'ʊ'},
            {'word': 0, 'phone': 's'},
            {'word': 0, 'phone': 'ʊ'},
            {'word': 1, 'phone': 'ɛ'},
            {'word': 1, 'phone': 'b'},
            {'word': 1, 'phone': 'ɪ'}],
  'focal': [3, 4],
  'phrases': [0, 0]}]

PROBE = {'id': 'constructed_A_locality',
 'slots': [{'word': 0, 'phone': 'e'},
           {'word': 1, 'phone': 'o'},
           {'word': 2, 'phone': 'e'},
           {'word': 3, 'phone': 'e'}],
 'focal': [0, 1, 2, 3],
 'phrases': [0, 0, 1, 1],
 'states': [['e', '∅', 'e', 'e'], ['e', '∅', 'o', 'e']],
 'origin_index': 0,
 'schema_index': 5,
 'status': 'constructed reader probe; not an attested form or full-product selecting test'}
