OBSERVATIONS_SELECTION = [{'id': 'G34a',
  'source': 'Obiri-Yeboah & Rasin (2025)',
  'source_segmental_input': 'ahɛ te ɔkpʊkɔ',
  'source_segmental_output': 'ahe tɔ ɔkpʊkɔ',
  'allowed': ['ahetɔɔkpʊkɔ'],
  'negative': [],
  'scope': 'full segment sequence; supplied phrasing recorded separately; '
           'tone/quantity/syllabification/lexical surface boundary not predicted',
  'categorical_singleton_is_hypothesis': True},
 {'id': 'G34b',
  'source': 'Obiri-Yeboah & Rasin (2025)',
  'source_segmental_input': 'afɪ sɛ ohili',
  'source_segmental_output': 'afɪ so ohili',
  'allowed': ['afɪsoohili'],
  'negative': ['afisoohili'],
  'scope': 'full segment sequence; supplied phrasing recorded separately; '
           'tone/quantity/syllabification/lexical surface boundary not predicted',
  'categorical_singleton_is_hypothesis': True},
 {'id': 'N7',
  'source': 'Obiri-Yeboah & Rasin (2025)',
  'source_segmental_input': 'atʃɪ jeli',
  'source_segmental_output': 'atʃi jeli',
  'allowed': ['atʃijeli'],
  'negative': [],
  'scope': 'full segment sequence; supplied phrasing recorded separately; '
           'tone/quantity/syllabification/lexical surface boundary not predicted',
  'categorical_singleton_is_hypothesis': True},
 {'id': 'G37c',
  'source': 'Obiri-Yeboah & Rasin (2025)',
  'source_segmental_input': 'ɔtʃʊ sɛ ibie',
  'source_segmental_output': 'ɔtʃʊ sejbie',
  'allowed': ['ɔtʃʊsejbie'],
  'negative': [],
  'scope': 'full segment sequence; supplied phrasing recorded separately; '
           'tone/quantity/syllabification/lexical surface boundary not predicted',
  'categorical_singleton_is_hypothesis': True},
 {'id': 'C24ei',
  'source': 'Obiri-Yeboah & Rasin (2025)',
  'source_segmental_input': 'kpe isi',
  'source_segmental_output': 'kpe jsi',
  'allowed': ['kpejsi'],
  'negative': [],
  'scope': 'full segment sequence; supplied phrasing recorded separately; '
           'tone/quantity/syllabification/lexical surface boundary not predicted',
  'categorical_singleton_is_hypothesis': True}]

OBSERVATIONS_DELETION = [{'id': 'OR38',
  'source': 'Obiri-Yeboah & Rasin (2025)',
  'source_segmental_input': 'atʃɔ sɪ iku',
  'source_segmental_output': 'atʃɔ siku',
  'allowed': ['atʃɔsiku'],
  'negative': [],
  'scope': 'full segment sequence; supplied phrasing recorded separately; '
           'tone/quantity/syllabification/lexical surface boundary not predicted',
  'categorical_singleton_is_hypothesis': True},
 {'id': 'C21b',
  'source': 'Obiri-Yeboah & Rasin (2025)',
  'source_segmental_input': 'wʊsʊ ɪsɛ',
  'source_segmental_output': 'wʊsʊ sɛ',
  'allowed': ['wʊsʊsɛ'],
  'negative': [],
  'scope': 'full segment sequence; supplied phrasing recorded separately; '
           'tone/quantity/syllabification/lexical surface boundary not predicted',
  'categorical_singleton_is_hypothesis': True},
 {'id': 'C23UE',
  'source': 'Obiri-Yeboah & Rasin (2025)',
  'source_segmental_input': 'wʊsʊ ɛbɪ',
  'source_segmental_output': 'wʊsw ɛbɪ',
  'allowed': ['wʊswɛbɪ'],
  'negative': [],
  'scope': 'full segment sequence; supplied phrasing recorded separately; '
           'tone/quantity/syllabification/lexical surface boundary not predicted',
  'categorical_singleton_is_hypothesis': True}]
