#!/bin/sh
set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
lean_root=$(CDPATH= cd -- "$script_dir/.." && pwd)
deliverables_root=$(CDPATH= cd -- "$lean_root/.." && pwd)
result_tsv="$deliverables_root/registry/result_registry.tsv"
proof_goal_tsv="$deliverables_root/registry/proof_goal_registry.tsv"
output="$lean_root/PhonologicalCalculus/Registry/Data.lean"

test -f "$result_tsv"
test -f "$proof_goal_tsv"

{
  printf '%s\n' '/- This file is generated by scripts/generate_registry_data.sh. -/'
  printf '%s\n' 'set_option maxRecDepth 10000'
  printf '%s\n\n' 'namespace PhonologicalCalculus.RegistryData'
  printf '%s\n' 'def resultIds : List String := ['
  awk -F '\t' 'NR > 1 { printf "  \"%s\",\n", $1 }' "$result_tsv"
  printf '%s\n\n' ']'
  printf '%s\n' 'def proof_goalIds : List String := ['
  awk -F '\t' 'NR > 1 { printf "  \"%s\",\n", $1 }' "$proof_goal_tsv"
  printf '%s\n\n' ']'
  printf '%s\n' 'theorem resultIds_length : resultIds.length = 68 := by decide'
  printf '%s\n' 'theorem proof_goalIds_length : proof_goalIds.length = 218 := by decide'
  printf '%s\n' 'theorem resultIds_nodup : resultIds.Nodup := by decide'
  printf '%s\n\n' 'theorem proof_goalIds_nodup : proof_goalIds.Nodup := by decide'
  printf '%s\n' 'end PhonologicalCalculus.RegistryData'
} > "$output"
