#!/bin/sh
set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
lean_root=$(CDPATH= cd -- "$script_dir/.." && pwd)
overrides="$lean_root/reports/coverage_overrides.tsv"
output="$lean_root/PhonologicalCalculus/MappingAudit.lean"

work_dir=$(mktemp -d "${TMPDIR:-/tmp}/lean-mapping-audit.XXXXXX")
trap 'rm -rf "$work_dir"' EXIT HUP INT TERM

awk -F '\t' '
  NR == 1 { next }
  $3 == "lean_closed" {
    prefix = ""
    count = split($4, declarations, ";")
    for (idx = 1; idx <= count; idx++) {
      declaration = declarations[idx]
      if (declaration ~ /^PhonologicalCalculus\./) {
        prefix = declaration
        sub(/\.[^.]+$/, "", prefix)
        print declaration
      } else if (prefix != "") {
        print prefix "." declaration
      } else {
        printf "Unqualified declaration without a namespace anchor: %s\n", \
          declaration > "/dev/stderr"
        failed = 1
      }
    }
  }
  END { if (failed) exit 1 }
' "$overrides" | LC_ALL=C sort -u > "$work_dir/targets"

{
  printf '%s\n' '/- This file is generated by scripts/generate_mapping_audit.sh. -/'
  printf '%s\n\n' 'import PhonologicalCalculus.All'
  sed 's/^/#check /' "$work_dir/targets"
} > "$output"

count=$(wc -l < "$work_dir/targets" | tr -d ' ')
printf 'Generated MappingAudit.lean with %s distinct declaration checks.\n' \
  "$count"
