import PhonologicalCalculus.All

/-!
# Public equation audit

Every `eq:*` label in `proofs/shared/equations/*.tex` is mapped in
`reports/equation_coverage.tsv` to at least one exact Lean declaration checked
below.  This is a declaration-and-correspondence audit: the status and scope
columns in the TSV distinguish definitions, theorem closure, registered finite
fixtures, empirical arithmetic replay, and explicit contract boundaries.
-/

-- eq:app-grid
#check PhonologicalCalculus.Application.app_mcc_grid
-- eq:app-kazakh
#check PhonologicalCalculus.Application.mccollum_profile_5_1
-- eq:app-uyghur
#check PhonologicalCalculus.Application.mccollum_profile_20_3
-- eq:app-basic
#check PhonologicalCalculus.Application.app_basic_reuse
-- eq:calc-preservation
#check PhonologicalCalculus.FiniteRequest.evaluate_eq_conservative_iff
-- eq:calc-witness-set
#check PhonologicalCalculus.FiniteRequest.mem_mismatchSet_iff
-- eq:calc-r01
#check PhonologicalCalculus.Regression.CALC_R01_PARTITION_01
-- eq:calc-r02
#check PhonologicalCalculus.Regression.CALC_R02_COIMAGE_01
-- eq:calc-r04
#check PhonologicalCalculus.Regression.CALC_R04_SURJECTIVITY_01
-- eq:calc-r11
#check PhonologicalCalculus.Regression.CALC_R11_FIBRE_01
-- eq:calc-r12
#check PhonologicalCalculus.Regression.CALC_R12_SERIES_01
-- eq:calc-r14
#check PhonologicalCalculus.Regression.CALC_R14_BELL_01
-- eq:chg-objective
#check PhonologicalCalculus.ContinuousHG.pathHarmony
-- eq:chg-simplex
#check PhonologicalCalculus.ContinuousHG.solidSimplex_profile_equivalence
-- eq:chg-reduced
#check PhonologicalCalculus.ContinuousHG.powerReducedObjective
-- eq:chg-first-zero
#check PhonologicalCalculus.ContinuousHG.generalPowerFirstZeroCell_iff_shiftedSum
-- eq:chg-kkt
#check PhonologicalCalculus.ContinuousHG.powerKKTDecrease_unique_minimizer
-- eq:chg-powered-gap
#check PhonologicalCalculus.ContinuousHG.normalizedProfileLoss_powered_gap
-- eq:chg-quadratic-support
#check PhonologicalCalculus.ContinuousHG.quadraticPositiveFollowerCount_iff_phaseCell
-- eq:chg-grid-boundary
#check PhonologicalCalculus.ContinuousHG.chg_b6_allBack_weak_iff
-- eq:chg-phase-cell
#check PhonologicalCalculus.ContinuousHG.generalPowerRatioPhaseCell_iff_threshold
-- eq:chg-profile
#check PhonologicalCalculus.ContinuousHG.powerProfileFromDecreases_eq_normalizedPhaseProfile
-- eq:chg-scaling-profile
#check PhonologicalCalculus.ContinuousHG.chg_b13_uniform_long_support_scaling
-- eq:chg-onset
#check PhonologicalCalculus.ContinuousHG.chg_b14_complete_ratio_onset_and_optimizer
-- eq:chg-linear-limit
#check PhonologicalCalculus.ContinuousHG.chg_b15_full_vector_optimizer_boundary_law
-- eq:chg-hard-limit
#check PhonologicalCalculus.ContinuousHG.chg_b16_unconditional_actual_hard_exponent_law
-- eq:ctx-two-trigger
#check PhonologicalCalculus.Context.absoluteIntervalPathHarmony
-- eq:ctx-phase
#check PhonologicalCalculus.Context.phaseShiftedPowerSum_eq_context
-- eq:ctx-support-law
#check PhonologicalCalculus.Context.ctx_c1_general_04_analytic
-- eq:data-portuguese
#check PhonologicalCalculus.Demonstration.data_pt_r1_replay
-- eq:data-english
#check PhonologicalCalculus.Demonstration.data_en_r1_replay
-- eq:data-mandarin
#check PhonologicalCalculus.Demonstration.data_zh_r1_replay
-- eq:fin-orbit-collision
#check PhonologicalCalculus.mem_collisionSet_iff
-- eq:fin-product-query
#check PhonologicalCalculus.productQuery_kernel_exact
-- eq:fin-factor
#check PhonologicalCalculus.kernelRefines_productQuery_iff
-- eq:fin-price
#check PhonologicalCalculus.blockwiseAddedConsumerPrice_eq
-- eq:fin-lattice
#check PhonologicalCalculus.productQuery_kernel_exact
-- eq:fin-symbolic-bridge
#check PhonologicalCalculus.fin_a2_coherence_03
-- eq:flux-shift
#check PhonologicalCalculus.Flux.shiftEquivariant_iff_periodic_deviation
-- eq:flux-periodic-family
#check PhonologicalCalculus.Flux.periodicFluxGauge_strictMono
-- eq:flux-ledger-nullspace
#check PhonologicalCalculus.Flux.finiteLedger_exists_nonzero_nullVector
-- eq:flux-contact-response
#check PhonologicalCalculus.Flux.flux_d4_complete_with_canonical_lambert
-- eq:flux-tomography
#check PhonologicalCalculus.Flux.terminalKKT_accumulatingResponse_identifies
-- eq:maxent-law
#check PhonologicalCalculus.MaxEnt.activityProbability_eq_exponentialProbability
-- eq:maxent-fibre
#check PhonologicalCalculus.MaxEnt.fibreMass
-- eq:maxent-cross-product
#check PhonologicalCalculus.MaxEnt.normalized_order_iff_cross_product
-- eq:maxent-strictifier
#check PhonologicalCalculus.MaxEnt.max_g3_strictifierPolynomial_complete
-- eq:maxent-tag-lift
#check PhonologicalCalculus.MaxEnt.CollectedSignedQuarticCode.taggedResidualMonomial_factorization
-- eq:maxent-selector
#check PhonologicalCalculus.MaxEnt.properCNFSelectorMargin_eq_polynomial
-- eq:maxent-basic-cone
#check PhonologicalCalculus.MaxEnt.max_g6_cone_02
-- eq:maxent-response-jet
#check PhonologicalCalculus.MaxEnt.max_g7_contact_02_mixedGerm
-- eq:maxent-capacity
#check PhonologicalCalculus.MaxEnt.max_g8_capacity_02_general
-- eq:maxent-incomparability
#check PhonologicalCalculus.MaxEnt.max_g9_lawtoenv_01
#check PhonologicalCalculus.MaxEnt.max_g9_envtolaw_02
-- eq:sel-events
#check PhonologicalCalculus.Selection.selectedEvent_subset_pairwise
-- eq:sel-ray-condition
#check PhonologicalCalculus.Selection.selectedEvent_eq_pairwise_iff_positiveRays
-- eq:sel-countergrammar
#check PhonologicalCalculus.Selection.counterexampleFaithfulness
#check PhonologicalCalculus.Selection.counterexampleMarkedness
-- eq:sel-score-rows
#check PhonologicalCalculus.Selection.sel_f2_scores_01
-- eq:sel-region-distances
#check PhonologicalCalculus.Selection.sel_f2_euclidean_02
-- eq:sup-objective
#check PhonologicalCalculus.Support.EndpointPathKKT
-- eq:sup-slope
#check PhonologicalCalculus.Support.sup_e1_completeEndpointWinnerBridge
-- eq:sup-matched
#check PhonologicalCalculus.Support.sup_e3_general_real_exponent
-- eq:sup-geometric
#check PhonologicalCalculus.Support.matchedPower_unique_global_minimizer
-- eq:sup-continuation
#check PhonologicalCalculus.Support.sup_e4_general_real_exponent
